/* ============================================================================
   MAINTEC SLEUTELTEST — VRAGENBANK
   ----------------------------------------------------------------------------
   Format per vraag:  [vraag_tekst, [optie_A, optie_B, optie_C, optie_D], correctIndex]
   correctIndex: 0 = A, 1 = B, 2 = C, 3 = D
   50 vragen per profiel × 6 profielen = 300 vragen totaal.
   Random selectie van 15 vragen per test sessie.
   ============================================================================ */

const QUESTIONS = {

  /* ════════════════════════════════════════════════════════════════════════
     ELEKTRO — HULPMONTEUR (50 vragen, basis niveau)
     ════════════════════════════════════════════════════════════════════════ */
  'E-hulpmonteur': [
    ["Welke kleur heeft de beschermingsaarde (PE) in een Nederlandse elektra-installatie?", ["Bruin","Blauw","Zwart","Geel/groen"], 3],
    ["Op welke spanning werkt een standaard wandcontactdoos in Nederland?", ["24 Volt","400 Volt","230 Volt","110 Volt"], 2],
    ["Wat is de eerste actie ALTIJD voordat je werkt aan een elektrische installatie?", ["Handschoenen aandoen","Multimeter pakken","Collega waarschuwen","Spanning afschakelen, vergrendelen en spanningsloosheid controleren (LOTO)"], 3],
    ["Welk gereedschap gebruik je om de isolatie van een kabel te verwijderen?", ["Combinatietang","Hamer","Striptang","Schroevendraaier"], 2],
    ["Wat betekent het IP-getal op elektrisch materiaal (bv. IP44)?", ["Vermogensklasse","Kabeldoorsnede","Spanningsklasse","Beschermingsgraad tegen aanraken, stof en water"], 3],
    ["Welk type kabel wordt gebruikt voor vaste installatie in een wand?", ["Verlengsnoer","UTP-kabel","H07RN-F","VMVK (NYM)"], 3],
    ["Welke kleur heeft een nuldraad (N)?", ["Bruin","Geel/groen","Blauw","Zwart"], 2],
    ["Welke kleur heeft de fasedraad in een moderne installatie?", ["Geel/groen","Wit","Bruin (of zwart/grijs in 3-fase)","Blauw"], 2],
    ["Wat is de functie van een aardlekschakelaar (ALS)?", ["Beveiligen tegen aardlekstromen om elektrocutie te voorkomen","Schakelen van verlichting","Beveiligen tegen overstroom","Spanningsregelaar"], 0],
    ["Hoe controleer je of een draad onder spanning staat?", ["Door te ruiken","Aan de kleur","Met een spanningstester of multimeter","Door aanraken"], 2],
    ["Wat moet je dragen tijdens werkzaamheden op de bouwplaats?", ["Sportschoenen","Alleen werkkleding","Gehoorbescherming alleen","Veiligheidshelm, veiligheidsschoenen S3 en zichtbaarheidskleding"], 3],
    ["Wat is een penspanningstester?", ["Een meetlint","Type zekering","Soort schroevendraaier","Klein apparaatje dat aangeeft of een geleider onder spanning staat"], 3],
    ["Wat is het maximum vermogen op een 16A groep bij 230V?", ["7360 W","1600 W","3680 W","16 W"], 2],
    ["Hoe trek je het beste een kabel door een leeg installatiebuis?", ["Met de hand alleen","Met perslucht zonder beveiliging","Met een schroevendraaier","Met een trekveer (kabelvis) en eventueel trekolie"], 3],
    ["Op welke standaardhoogte komt een wandcontactdoos in een woonruimte?", ["Circa 30 cm boven afgewerkte vloer","Circa 100 cm","Circa 5 cm","Circa 180 cm"], 0],
    ["Welk gereedschap gebruik je om gaten in beton te boren voor installatiebuis?", ["Lijmtang","Klop-/breekboor (SDS)","Decoupeerzaag","Houtboor"], 1],
    ["Wat doe je als je beschadigd gereedschap aantreft?", ["Doorgebruiken tot eind dag","Doorgeven aan collega","Zelf snel repareren","Direct uit gebruik nemen, melden en laten keuren"], 3],
    ["Wat is een Wago lasklem?", ["Type zekering","Een meetinstrument","Een steekklem voor het verbinden van geleiders zonder schroef","Soort schakelaar"], 2],
    ["Wat is het verschil tussen inbouw- en opbouwmateriaal?", ["Geen verschil","Opbouw heeft hogere spanning","Inbouw is voor buiten","Inbouw zit verzonken in de wand, opbouw zit op de wand"], 3],
    ["Op dit project geldt een TOTAAL LASVERBOD. Hoe bevestig je dan kabelgoten aan de constructie?", ["Met schroef-/boutverbindingen of klemsystemen","Met TIG-lassen","Met MIG-lassen","Met thermiet"], 0],
    ["Waarom is er een lasverbod op dit project?", ["De gebouwen hebben houten vloeren — brandgevaar","Lassen is te duur","Lasrook is verboden","Geen geschikt lasapparaat aanwezig"], 0],
    ["Wat doe je voordat je een gat door een muur boort?", ["Locatie van leidingen/draden controleren met detectie","Kleinere boor pakken","Vragen of een collega kijkt","Direct boren"], 0],
    ["Welke minimale aderdoorsnede gebruik je voor een verlichtingsgroep?", ["0,75 mm²","6 mm²","0,5 mm²","1,5 mm²"], 3],
    ["Welke minimale aderdoorsnede gebruik je voor een 16A wandcontactdoosgroep?", ["0,75 mm²","10 mm²","2,5 mm²","1,5 mm²"], 2],
    ["Wat is een aftakdoos (lasdoos)?", ["Type stekkerdoos","Doos waarin geleiders met elkaar verbonden worden","Een soort zekering","Voedingsbron"], 1],
    ["Wat doe je met restafval (kabelresten, verpakking) op de bouwplaats?", ["In de prullenbak","Laten liggen","Scheiden en in juiste afvalcontainer afvoeren","Mee naar huis"], 2],
    ["Wat is een DALI-systeem?", ["Een schakelaar","Soort zekering","Type kabel","Een protocol voor digitale verlichtingssturing"], 3],
    ["Welk symbool op een tekening staat voor een wandcontactdoos?", ["Driehoek","Vierkant met diagonaal","Cirkel met radiale lijnen","Kruis"], 2],
    ["Wat is het doel van een installatiebuis?", ["Versteviging van de wand","Waterleiding","Mechanische bescherming van kabels en latere vervanging mogelijk maken","Ventilatie"], 2],
    ["Hoe sluit je een enkelvoudige schakelaar aan op een lamp?", ["Fase via schakelaar naar lamp, nul direct naar lamp","Nul via schakelaar","Beide via schakelaar","Aarde via schakelaar"], 0],
    ["Wat is een bewegingsmelder (PIR)?", ["Stopcontact met sensor","Sensor die beweging detecteert om verlichting te schakelen","Brandmelder","Type zekering"], 1],
    ["Wat doe je als je een onveilige situatie ziet?", ["Stoppen, werkomgeving veiligstellen en direct melden aan de uitvoerder","Niets, dat is iemand anders zijn taak","Zelf oplossen","Doorwerken tot pauze"], 0],
    ["Hoe communiceer je met een Engelstalige collega-leidinggevende?", ["In duidelijk Engels, met tekening of gebaren bij twijfel","Negeren","Alleen in het Nederlands","Via WhatsApp tekstvertaler tijdens werk"], 0],
    ["Wat is het verschil tussen klasse I en klasse II apparaten?", ["Klasse I gebruikt 110V","Geen verschil","Klasse I heeft aarding nodig, klasse II is dubbel geïsoleerd","Klasse II is voor industrie"], 2],
    ["Wanneer gebruik je een veiligheidsharnas?", ["Altijd","Nooit","Bij werken op hoogte > 2,5 m zonder andere randbeveiliging","Alleen op de begane grond"], 2],
    ["Wat moet je doen voor je een ladder gebruikt?", ["Direct beklimmen","Boven op de ladder springen","Op de bovenste tree gaan staan","Visueel keuren, juiste hoek (75°), stabiel opstellen"], 3],
    ["Welke kabel mag je NIET gebruiken voor permanente vaste aanleg?", ["NYM (VMVK)","H05VV-F (verlengsnoer-kwaliteit)","XGB","NYAF in een buis"], 1],
    ["Wat is een conduit (installatiebuis)?", ["Een buis waarin elektrische geleiders worden geïnstalleerd","Type stopcontact","Een soort kabel","Soort lamphouder"], 0],
    ["Wat is een schakelmateriaal-set?", ["Soort kabel","Combinatie van inbouwdoos, sokkel en afdekraam","Voedingsbox","Aftakdoos met deksel"], 1],
    ["In een monumentaal gebouw (Gebouw J) — hoe leg je nieuwe leidingen aan?", ["Boren waar je wilt","Hak alle muren open","Buitenom langs gevel","Zo onzichtbaar mogelijk, met respect voor monumentale waarde, in overleg"], 3],
    ["Welke informatie staat op een kabelhaspel/rol?", ["Alleen gewicht","Alleen kleur","Type, doorsnede, lengte, fabrikant","Alleen prijs"], 2],
    ["Wat is een kabelclip?", ["Snijgereedschap","Soort connector","Bevestigingsmiddel om een kabel netjes aan een ondergrond te bevestigen","Markeringssticker"], 2],
    ["Wat is de minimale buigstraal van een installatiekabel meestal?", ["2× kabeldiameter","Maakt niet uit","Zo strak mogelijk","Ca. 6× kabeldiameter"], 3],
    ["Welk PBM hoort minimaal bij elektra-werk in een schakelkast?", ["Alleen schoenen","Veiligheidsbril, isolerende handschoenen waar nodig","Alleen helm","Geen"], 1],
    ["Wat doe je met afgekeurde elektrische apparaten/snoeren?", ["Nog even gebruiken","Apart afvoeren, niet meer in gebruik nemen","Doorverkopen","Repareren met tape"], 1],
    ["Wat is potentiaalvereffening?", ["Stroomverdeling","Verbinden van metalen delen met de aarde om spanningsverschillen te voorkomen","Een bedraad veiligheidsslot","Spanningsregeling"], 1],
    ["Hoe ga je om met afval op de werkvloer aan het einde van de dag?", ["In een open vuur","Laten liggen","Op de gang zetten","Werkplek opruimen, scheiden en afvoeren"], 3],
    ["Wat doe je als je gereedschap of materiaal kwijt bent?", ["Stilhouden","Zelf vervangen","Melden aan de chef-monteur of uitvoerder","Een ander pakken"], 2],
    ["Wat is het doel van toolboxmeetings?", ["Functioneringsgesprek","Korte veiligheids- en werkbespreking voorafgaand aan werk","Sociale momenten","Pauze"], 1],
    ["Wat doe je als de spanning onverwacht uitvalt tijdens werkzaamheden?", ["Gewoon doorwerken","Zelf de hoofdschakelaar resetten","Pauze nemen","Werk staken, situatie controleren en chef-monteur informeren"], 3],
  ],

  /* ════════════════════════════════════════════════════════════════════════
     ELEKTRO — MONTEUR (50 vragen, vakkennis-niveau)
     ════════════════════════════════════════════════════════════════════════ */
  'E-monteur': [
    ["Welke norm regelt elektrische installaties in laagspanning in Nederland?", ["NEN 1006","NEN 3140","NEN 50110","NEN 1010"], 3],
    ["Welke norm regelt het VEILIG werken aan en met elektrische installaties?", ["NEN 1010","NEN 2535","ISO 9001","NEN 3140"], 3],
    ["Wat is de maximale lijnimpedantie (Zs) waarbij een 16A B-automaat in 0,4 s afschakelt?", ["≈ 2,87 Ω","Onbeperkt","≈ 0,2 Ω","≈ 23 Ω"], 0],
    ["Bij welke lekstroom moet een Type A aardlekschakelaar uiterlijk afschakelen?", ["30 mA in maximaal 300 ms","500 mA","1 A","100 mA"], 0],
    ["Welk meetinstrument gebruik je voor isolatieweerstandmeting?", ["Frequentiemeter","Megger (isolatieweerstandsmeter)","Voltmeter","Ampèretang"], 1],
    ["Wat is de minimale isolatieweerstand bij 500 V meetspanning op een nieuwe installatie volgens NEN 1010?", ["≥ 1 MΩ","≥ 100 Ω","≥ 1 kΩ","≥ 1 GΩ"], 0],
    ["Wat is de eis voor de aardingsweerstand bij een TT-stelsel?", ["RA × IΔn ≤ 50 V (in praktijk meestal Ra ≤ 167 Ω bij 30 mA)","Maakt niet uit","Altijd < 1 Ω","< 1000 Ω"], 0],
    ["Wat is selectiviteit in een installatie?", ["Alle automaten gaan tegelijk uit","Niets schakelt af","Alleen de hoofdaansluiting","Bij een fout schakelt alleen de dichtstbijzijnde beveiliging af"], 3],
    ["Welke beveiliging gebruik je tegen overstroom én kortsluiting?", ["Magneetschakelaar","Filter","Aardlekschakelaar","Installatieautomaat (MCB)"], 3],
    ["Wat is het verschil tussen een B-, C- en D-karakteristiek?", ["Verschillende prijs","Verschillende uitschakelstroom (3-5×, 5-10×, 10-20× In)","Verschillende kleur","Verschillende spanning"], 1],
    ["Hoeveel adergroepen heeft een TN-S systeem?", ["Alleen L en PE","Gecombineerde PEN","2 fasen, 1 N","L, N en aparte PE-geleider"], 3],
    ["Welk meetinstrument gebruik je om de continuïteit van een PE-geleider te controleren?", ["Frequentiemeter","Watt-meter","Lage-ohmmeter (PE-continuïteitsmeter)","Spanningsmeter"], 2],
    ["Wat is het belangrijkste keuringsdocument na oplevering van een nieuwe installatie?", ["Pakbon","E-mailbevestiging","Inspectierapport conform NEN 1010 / NTA 8220 met meetwaarden","Tekening"], 2],
    ["Welke kabel gebruik je bij brandwerende installaties (bv. noodverlichting)?", ["Functiebehoud-kabel (bv. (N)HXH FE180/E30)","Standaard NYM","Coax","H05VV-F"], 0],
    ["Hoe wordt een 3-fase voeding aangeduid?", ["Plus en min","L1, L2, L3 + N + PE","A, B, C","R, S, T + 0"], 1],
    ["Wat is de spanning tussen twee fasen in een 400/230V net?", ["≈ 690 V","≈ 230 V","≈ 400 V","≈ 110 V"], 2],
    ["Hoe sluit je een 3-fase wandcontactdoos (CEE 16/5) correct aan?", ["Volgorde maakt niet uit","Alleen 3 fasen, geen N en PE","L1, L2, L3, N, PE conform IEC 60309-aansluitschema","Eerst aarden tijdens inschakelen"], 2],
    ["Wat is een KWh-meter (kilowattuurmeter)?", ["Frequentiemeter","Spanningmeter","Aardingsmeter","Meter die elektrische energie registreert"], 3],
    ["Welk type kabel gebruik je voor onder-grond aanleg?", ["YMvKas of XMvK (grondkabel)","NYAF","NYM","H07RN-F"], 0],
    ["Wat is een PEN-geleider?", ["Plusgeleider","Gecombineerde nul- en aardingsgeleider in TN-C systeem","Alleen aarde","Alleen nul"], 1],
    ["Hoe groot is de maximale spanningsval over een eindgroep volgens NEN 1010 (richtlijn)?", ["20%","10%","Geen limiet","3% bij verlichting / 5% bij overige"], 3],
    ["Wat doe je als de gemeten Re (aardingsweerstand) te hoog is?", ["Negeren","Meer aardlekschakelaars","Aardelektrode uitbreiden of bijplaatsen, opnieuw meten","Lagere zekering plaatsen"], 2],
    ["Wat is het LOTO principe?", ["Een tekensoftware","Een schakelvolgorde","Lock-Out / Tag-Out: vergrendelen en labelen van energiebronnen","Soort kabel"], 2],
    ["Wat is het verschil tussen actieve en reactieve vermogen?", ["Reactief is verlies door kabel","Actief (W) doet werk; reactief (var) bouwt magnetische velden","Actief is alleen DC","Geen verschil"], 1],
    ["Wat is een THD (Total Harmonic Distortion)?", ["Soort schakelaar","Maat voor harmonische vervorming op een net","Type vermogen","Soort meting van warmte"], 1],
    ["Welk symbool ⊕ kan voor een elektromotor staan op een tekening?", ["Cirkel met S","Cirkel met R","Cirkel met T","Cirkel met M"], 3],
    ["Wat is de voorkeur voor het laggen van CAT6-data en sterkstroom?", ["Allemaal samen","Alleen via dezelfde kabel","Maakt niet uit","Gescheiden goten / minimale parallelle afstand om EMC-storing te voorkomen"], 3],
    ["Wat is een NEN 3140-keuring?", ["Eenmalige nieuwbouwkeuring","Een examen","Een softwareversie","Periodieke inspectie van elektrische arbeidsmiddelen en installaties"], 3],
    ["Welk gereedschap is verplicht VG-gekeurd voor elektra-werk?", ["Persoonlijke elektrische gereedschappen en meetapparatuur (jaarlijks of conform leverancier)","Schroevendraaier zonder pen","Hamer","Niets"], 0],
    ["Wat is de typische schakelvolgorde bij in bedrijf nemen van een groepenkast?", ["Hoogste eerst","Hoofdschakelaar → ALS → automaten van laag naar hoog vermogen","Niet relevant","Random"], 1],
    ["Hoe los je een ongebalanceerde belasting in 3-fase op?", ["Hogere zekering","Zware belastingen herverdelen over de fases","Extra N-geleider","Niets, automaat lost het op"], 1],
    ["Wat is een busbar?", ["Stroomrail (geleidende strip) in een verdeelinrichting","Soort buis","Type kabel","Soort lasapparaat"], 0],
    ["Wat is de maximale belasting van een C16-automaat continu?", ["16 A","160 A","32 A","8 A"], 0],
    ["Wat is een functiebehoud-installatie?", ["Een glasvezelnet","UPS","Installatie die bij brand een bepaalde tijd blijft functioneren (bv. 30/60/90 min)","Een verbeterde isolatie"], 2],
    ["Wat is het verschil tussen bewaakte en onbewaakte noodverlichting?", ["Geen verschil","Onbewaakt is verboden","Bewaakt is centraal gemonitord; onbewaakt is autonoom (eigen accu)","Bewaakt is duurder en standaard"], 2],
    ["Welke beveiligingsklasse heeft een dubbel geïsoleerd apparaat?", ["Klasse I","Klasse IV","Klasse II (vierkant in vierkant)","Klasse III"], 2],
    ["Wat is een KNX-systeem?", ["Soort kabel","Open busprotocol voor gebouwautomatisering","Soort zekering","Een vrije applicatie"], 1],
    ["Hoe meet je vermogensfactor (cos φ)?", ["Met een gewone voltmeter","Met multimeter Ω-stand","Met een ampèretang alleen","Met een netanalyser (Power Quality Analyser)"], 3],
    ["Welke aarde gebruik je voor een aanraakgevoelige metalen wastafel in een vochtige ruimte?", ["Alleen N","Eigen aardpen","Aansluiten op de potentiaalvereffening van de ruimte","Geen aarde nodig"], 2],
    ["Wat is een SELV-circuit?", ["Een 400V circuit","Veilige extra-lage spanning, gescheiden van het net (≤ 50 V AC)","Een hoogspanningscircuit","Een 230V circuit"], 1],
    ["Hoe markeer je een spanningsloos gestelde groep?", ["Niet markeren","Met een vergrendelslot en label (LOTO) en daarna spanningsloos meten","Met stift","Met tape"], 1],
    ["Hoe ga je om met asbestverdacht materiaal in oudbouw?", ["Inpakken en doorgaan","Met masker doorwerken","Zelf saneren","Werk stilleggen, melden bij uitvoerder, gespecialiseerd team inschakelen"], 3],
    ["Wat is een sleufafdekking en wanneer pas je het toe?", ["Een isolerend tape","Een type kabel","Ter bescherming bij open kabel-/leidingsleuven, te plaatsen voorafgaand aan dichtmaken","Een veiligheidshelm"], 2],
    ["Wat moet je controleren bij een nieuwe wandcontactdoos vóór ingebruikname?", ["Polariteit, aarding, spanning en goede klemkracht; visueel + meting","Alleen spanning","Alleen kleur","Niets"], 0],
    ["Wat is een impedantielus-meting (Zs)?", ["Meting van fase-PE impedantie om uitschakelvoorwaarde te valideren","Lichtsterkte meting","Spanningsmeting alleen","Aardingsmeting alleen"], 0],
    ["Hoe pak je werk aan in een monumentaal pand (bv. Gebouw J)?", ["Boren waar je wilt","Inventarisatie, onomkeerbare ingrepen vermijden, oplossingen in overleg met monumentenzorg","Slopen waar nodig","Snel werken zonder toestemming"], 1],
    ["Wat is een PE-S installatieconcept?", ["Een meetapparaat","Een type voeding","Een soort schakelaar","Een TN-S systeem met aparte PE-geleider — voorkeur voor moderne installaties"], 3],
    ["Wat doe je als je metingen afwijken van de norm?", ["Doorgaan","Negeren","Andere meter pakken","Stoppen, oorzaak onderzoeken, herstellen en opnieuw meten — registreren"], 3],
    ["Welk document overhandig je bij oplevering aan de opdrachtgever?", ["Alleen tekening","Alleen factuur","Inspectierapport, asbuilt-tekeningen en gebruikershandleiding","Niets"], 2],
    ["Hoe stem je dagelijks af met een Engelstalige collega-leidinggevende?", ["Alleen via WhatsApp","Niet","Met een tolk per uur","Korte dagstart in Engels, met tekeningen en checklists, en heldere afspraken"], 3],
  ],

  /* ════════════════════════════════════════════════════════════════════════
     ELEKTRO — CHEF-MONTEUR (50 vragen, leiding & advanced)
     ════════════════════════════════════════════════════════════════════════ */
  'E-chef': [
    ["Welke verantwoordelijkheid heeft een chef-monteur in NEN 3140?", ["Alleen administratie","Geen wettelijke rol","Aanwijzing als 'Vakbekwaam Persoon' (VP), met opdrachtbevoegdheid voor specifieke werkzaamheden","Alleen toezicht"], 2],
    ["Wie is verantwoordelijk voor de werkvoorbereiding van zijn ploeg op locatie?", ["Hulpmonteur","De chef-monteur, in afstemming met uitvoerder en hoofduitvoerder","Calculatie-afdeling","Opdrachtgever"], 1],
    ["Wat doe je voordat een ploeg start in een nieuwe ruimte op dit project?", ["Direct beginnen","LMRA en toolbox, RIE doornemen, taakverdeling, controles op leidingen/asbest/monument","Materiaal pas later bestellen","Pauze"], 1],
    ["Welke risico's signaleer je in een monumentaal pand (Gebouw J)?", ["Alleen kostenrisico","Schade aan monumentale onderdelen, brandgevaar, stof in publieksruimten","Alleen tijd","Geen"], 1],
    ["Wat is een LMRA?", ["Een meting","Een rapportagevorm","Een type kabel","Last Minute Risk Analysis vlak voor start van een taak"], 3],
    ["Hoe verdeel je 100 vragen-niveau leiding bij anderstalige collega-uitvoerders?", ["Tolk inhuren per uur","Heldere visuele werkinstructies + Engelse dagstart + dagelijkse afstemming","Niet communiceren","Alles via mail"], 1],
    ["Hoe controleer je de kwaliteit van werk van je ploeg?", ["Alleen klachtgestuurd","Eenmaal aan einde","Periodieke steekproeven, opleverchecks, registratie afwijkingen, terugkoppeling","Vertrouwen volstaat"], 2],
    ["Welke selectiviteit heeft voorrang in een ziekenhuis-achtige kritieke installatie?", ["Tijdsvertraging op alle automaten","Volledige selectiviteit (alleen onderste schakelt af) ook bij kortsluiting","Geen selectiviteit","Alles via één hoofdautomaat"], 1],
    ["Welke berekening voer je uit voor kabeldoorsnedebepaling?", ["Visueel","Alleen belasting","Alleen lengte","Belasting, omgevingstemperatuur, bundeling, spanningsval en kortsluitvastheid"], 3],
    ["Wat is de uitschakelvoorwaarde bij een 0,4 s eis?", ["Geen eis","Spanningsmaat alleen","Zs ≤ U₀ / Ia, waarbij Ia de uitschakelstroom van de beveiliging is","Tijdsmaat"], 2],
    ["Hoe lever je een verdeelinrichting op?", ["Foto in app","Alleen schoonmaken","Visuele inspectie, meetrapport, schema in de kast, labels op groepen, NEN 1010 rapport","Niet labelen"], 2],
    ["Welke documentatie verwacht een hoofdaannemer bij oplevering elektra?", ["As-built tekeningen, schema's, meetrapport, garantieverklaringen, O&M","Alleen e-mail","Niets","Alleen factuur"], 0],
    ["Wat is een KEMA-keur of KIWA-certificering?", ["Verplicht voor monteurs","Onafhankelijk certificaat van producten/installaties","Een gereedschapssticker","Veiligheidsbeker"], 1],
    ["Hoe maak je een dagplanning voor 6 monteurs in een renovatieproject?", ["Iedereen overal tegelijk","Op gevoel","Bij aankomst beslissen","Werkpakketten per ruimte/gebouw, materiaalvoorziening, afhankelijkheden, buffer"], 3],
    ["Wat is een werkvergunning (Permit-To-Work)?", ["Toolboxformulier","Een tekening","Loonstrook","Document dat specifieke werkzaamheden onder voorwaarden toestaat"], 3],
    ["Hoe ga je om met een bouwafwijking (deviation)?", ["Zelf beslissen","Verzwijgen","Stoppen, registreren in afwijkingenlogboek, oplossing met uitvoerder/engineering","Doorpushen"], 2],
    ["Welke beveiliging plan je voor een serverruimte?", ["Aardlek 300 mA","Eigen TN-S groepenkast met redundantie, UPS, monitoring, vroegtijdige branddetectie","Alleen één automaat","Geen beveiliging"], 1],
    ["Wat is een kortsluitstroomberekening?", ["Spanningsmaat","Inspectiemaat","Berekening van Ik max/min om beveiligingen correct te dimensioneren","Vermogensmaat"], 2],
    ["Welke softwarepakketten ken je voor installatieontwerp?", ["Photoshop","Word","Excel","Stabicad, Revit MEP, AutoCAD MEP"], 3],
    ["Welke afspraken maak je met de hoofduitvoerder over toegang in monumentale ruimtes?", ["Random","Achteraf","Tijdvensters, toezicht, beschermmaatregelen voor vloeren/wanden, registratie","Geen"], 2],
    ["Wat houdt 'eindcontrole' (NEN 1010) in?", ["Alleen metingen","Zicht- en functioneringscontrole + metingen + rapportage","Alleen factuur","Alleen visueel"], 1],
    ["Hoe rapporteer je voortgang aan de uitvoerder?", ["Dagelijks: voortgang, problemen, planning, blokkades — in vast format","Random","Niet","Maandelijks"], 0],
    ["Hoe ga je om met meerwerk dat een hulpmonteur signaleert?", ["Direct uitvoeren","Beoordelen, registreren in meerwerkstaat, afstemmen met uitvoerder vóór uitvoering","Negeren","Klant bellen"], 1],
    ["Wat is de juiste volgorde van inbedrijfstelling?", ["Direct inschakelen","Alleen visueel","Visueel → spanningsloos meten → potentiaal/aarde → isolatie → onder spanning → functie","Random"], 2],
    ["Hoe verdeel je verantwoordelijkheden in je ploeg?", ["Random","Op leeftijd","Op basis van competenties (NEN 3140-niveau), met toezicht hulpmonteurs door VP","Alleen senioriteit"], 2],
    ["Wat is een elektrische bedieningsruimte volgens NEN 1010?", ["Algemene toiletruimte","Vergaderkamer","Ruimte met specifieke eisen voor toegang en deskundige bediening","Een opslagruimte"], 2],
    ["Wat is BHV en hoe relateert dat aan jouw rol?", ["Een NEN-norm","BedrijfsHulpVerlening — chef-monteur is meestal mede-BHV-er en weet waar AED's hangen","Niet relevant","Een softwarepakket"], 1],
    ["Welke EHBO-stappen volg je bij elektrocutie?", ["Pleister plakken","Wegrennen","Spanning vrij maken, 112 bellen, reanimeren tot hulp er is","Patiënt aanraken zonder afschakelen"], 2],
    ["Hoe stem je af bij gelijktijdig werken met W-monteurs (klimaatplafonds)?", ["Werkvolgorde plannen, kabelgoten en koel-/CV-leidingen niet kruisen op kritieke plaatsen","Eind van project pas","Iedereen op eigen houtje","Alleen vrijdag"], 0],
    ["Wat is een opleverpunt?", ["Een toolboxnotitie","Toolbox","Een schroef","Een gerelateerd werk-/herstelpunt opgenomen op de opleverlijst"], 3],
    ["Wat doe je bij een bijna-ongeval?", ["Direct registreren, oorzaakanalyse, maatregel, lessons learned communiceren","Niet melden","Pas registreren bij echt ongeval","Stilhouden"], 0],
    ["Hoe stem je af met de leverancier voor maatwerk in een monumentale ruimte?", ["Standaard kopen","Op het laatste moment","Random keuze","Specs vroegtijdig vastleggen, mock-up indien nodig, levertijden in planning"], 3],
    ["Wat is een RIE?", ["Risico-Inventarisatie en Evaluatie — verplicht document op de bouwplaats","Een type meter","Een formulier voor financiën","Een tekening"], 0],
    ["Wat is je rol bij keuring van gereedschap?", ["Alleen incidenteel","Geen","Alleen bij klachten","Toezien op geldige NEN 3140-stickers, defect gereedschap onmiddellijk uit roulatie"], 3],
    ["Hoe valideer je de aansluitwaarde voor een nieuwe installatie?", ["Berekend opgenomen vermogen + gelijktijdigheidsfactor → afspraak met netbeheerder","Schatting","Marktwaarde","Maximale waarde"], 0],
    ["Wat is een werkpakket?", ["Een loonstrook","Afgebakende set werkzaamheden met scope, materiaal, tijd en planning","Een tas","Een schroefset"], 1],
    ["Wat is een bouwbespreking?", ["Sociaal moment","Periodiek overleg tussen uitvoering en partijen om voortgang en problemen te bespreken","Pauze","Officiële opening"], 1],
    ["Hoe behandel je klachten van eindgebruikers tijdens een proefbedrijf?", ["Op eigen houtje","Negeren","Registreren, prioriteren, planmatig oplossen en terugkoppelen","Onmiddellijk eindeloos"], 2],
    ["Wat is een digitale tweeling (digital twin) in renovatieprojecten?", ["Een type kabel","Een meetapparaat","Een formulier","Digitaal model dat synchroon loopt met het fysieke gebouw, voor onderhoud"], 3],
    ["Wat is een SCIOS keuring?", ["Een verplicht spel","Onafhankelijke keuring van technische installaties op veiligheid","Een softwarekeuring","Een muziekkeuring"], 1],
    ["Wat is een F-gassen certificaat en is het relevant voor jou?", ["Voor koudemiddelhandelingen — relevant bij W-koeling, niet bij elektra","Verplicht voor elektriciens","Niet bestaand","Een NEN 1010 onderdeel"], 0],
    ["Welke planning gebruik je voor een renovatie met 7 gebouwen?", ["Van achteren naar voren","Eén plan, alle gebouwen","Per dag spontaan","Faseplanning per gebouw met afhankelijkheden, kritieke pad analyse"], 3],
    ["Hoe rapporteer je een veiligheidsincident?", ["Volgens RI&E protocol, in incidentenregister, met directe maatregelen en review","Mondeling alleen","Niet rapporteren","Pas na een week"], 0],
    ["Wat is je strategie als materiaal niet op tijd is?", ["Buffer-werkpakketten, alternatieven, contact met inkoop/uitvoerder","Random ander werk","Mensen naar huis","Stilstand accepteren"], 0],
    ["Welke veiligheidsmaatregel neem je bij werken naast publiek (blijvend gebruik)?", ["Alleen 's avonds werken","Alleen achter slot","Werkvak afzetten, stof- en geluidshinder beperken, communicatie naar gebruikers","Niets"], 2],
    ["Wat is een VCA-VOL?", ["Een type bouwkraan","Veiligheidscertificering Voor Operationeel Leidinggevenden — vereist voor chef-monteur","Een softwarelicentie","Een lasdiploma"], 1],
    ["Hoe houd je je ploeg gemotiveerd op een lange renovatie?", ["Niets doen","Heldere doelen, erkenning, korte feedbackcycli, leerruimte","Hard schreeuwen","Bonus achteraf"], 1],
    ["Welke beveiliging is verplicht voor stopcontacten in vochtige ruimten?", ["Alleen ventilatie","Aardlekschakelaar 30 mA + IP-juiste materialen","Geen","Alleen automaat"], 1],
    ["Wat doe je als je een ontwerp-fout in tekening ziet?", ["Documenteren, melden bij ontwerpend partij, oplossing afspreken voor uitvoering","Zelf bedenken","Negeren","Doorgaan onveilig"], 0],
    ["Wat is jouw rol in 'duurzaam slopen' van bestaande elektra?", ["Materialen scheiden voor hergebruik/recycling, asbest-protocol volgen, registratie","Verbranden","Alles in één container","Aan kant gooien"], 0],
  ],

  /* ════════════════════════════════════════════════════════════════════════
     WERKTUIGBOUW — HULPMONTEUR (50 vragen)
     ════════════════════════════════════════════════════════════════════════ */
  'W-hulpmonteur': [
    ["Welke gereedschap gebruik je voor het buigen van koperen leidingen?", ["Pijpenbuiger (handmatig of mechanisch)","Boormachine","Tang","Hamer"], 0],
    ["Welke verbindingsmethode is GEEN optie op dit project?", ["Klemkoppelingen","Lassen (totaal lasverbod)","Solderen met passend procedé","Persen"], 1],
    ["Waarom geldt een totaal lasverbod op dit project?", ["Houten vloeren — brandgevaar","Te kostbaar","Geen reden","Geen lasapparaat aanwezig"], 0],
    ["Wat is een persfitting?", ["Een lasconstructie","Een schroefverbinding","Een rubberen overgang","Een fitting die met perstang permanent op de buis wordt geperst"], 3],
    ["Welk gereedschap gebruik je voor persen van koperen leidingen?", ["Schroevendraaier","Steeksleutel","Persgereedschap met juiste persbek (M-, V- of TH-profiel)","Bahco"], 2],
    ["Wat is het verschil tussen aanvoer- en retourleiding in CV?", ["Geen verschil","Aanvoer is dikker","Retour is warmer","Aanvoer is warm water uit de ketel, retour is afgekoeld water terug"], 3],
    ["Welke kleur zijn vaak aanvoerleidingen aangeduid?", ["Blauw","Rood","Groen","Geel"], 1],
    ["Welke kleur zijn vaak retourleidingen aangeduid?", ["Geel","Blauw","Rood","Groen"], 1],
    ["Wat is een T-stuk (fitting)?", ["Een fitting waarbij drie leidingen samenkomen","Een type meter","Een soort kraan","Een steuninstrument"], 0],
    ["Welk materiaal mag je voor drinkwaterleiding gebruiken?", ["Tuinslang","Standaard PVC","KIWA-gecertificeerd (bv. koper, RVS, multilayer-PEX)","Lood"], 2],
    ["Wat is isolatie van leidingen?", ["Beschermlaag tegen ratten","Reclame-uiting","Verfraaiing","Materiaal om warmteverlies of condens te voorkomen"], 3],
    ["Welk basisgereedschap gebruik je voor schroefverbindingen op leidingen?", ["Steek-/ringsleutel of pijptang","Soldeerbout","Boor","Hamer"], 0],
    ["Wat is teflontape (PTFE-tape)?", ["Isolatiemateriaal","Reinigingsmiddel","Beschermlaag tegen UV","Afdichtmateriaal op schroefdraad"], 3],
    ["Welk gereedschap gebruik je om een buis af te zagen?", ["Decoupeerzaag","Cirkelzaag","Houtzaag","Pijpsnijder of fijne metaalzaag"], 3],
    ["Wat doe je na het zagen van een koperen buis?", ["Bramen verwijderen (binnen en buiten)","Direct verbinden","Nat maken","Verfen"], 0],
    ["Welke PBM gebruik je bij persen/zagen van leidingen?", ["Veiligheidsbril en handschoenen","Geen","Alleen helm","Alleen oordoppen"], 0],
    ["Wat doe je voor je een afsluiter bedient?", ["Negeren","Hard opendraaien","Controleren wat downstream is, klant/collega's informeren, langzaam openen","Wegrennen"], 2],
    ["Hoe herken je een gaswaterleiding versus drinkwaterleiding?", ["Aan vorm","Aan markering, kleur en certificering — bij twijfel niet zelf aansluiten","Op gevoel","Geen verschil"], 1],
    ["Wat is een klimaatplafond?", ["Plafond met geïntegreerd verwarm/koelsysteem (water- of luchtgevoed)","Decoratief plafond","Akoestisch plafond","Geluidsdempend plafond"], 0],
    ["Welke leidingmaten zie je veel in CV-installatie?", ["15, 18, 22, 28 mm koper of vergelijkbaar PEX/multilayer","Alleen 6 mm","Alleen 50 mm","DN 100"], 0],
    ["Wat is een prefab leidingunit?", ["Een meter","Een type kraan","Een isolatiemateriaal","Vooraf in fabriek geassembleerde leidingmodule, op locatie alleen koppelen"], 3],
    ["Welke functie heeft een ontluchter?", ["Lucht uit het CV-systeem laten ontsnappen","Brand beveiligen","Geluid dempen","Water afvoeren"], 0],
    ["Wat is een groepverdeler/verdeelstation?", ["Soort meter","Centraal punt voor verdeling van CV-/koudwater naar groepen","Reductietoestel","Een type isolatie"], 1],
    ["Wat is een reduceerventiel?", ["Filtert water","Verwarmt water","Verlaagt de waterdruk naar een lagere stabiele waarde","Stopt water"], 2],
    ["Welke richting draai je een schroefdraad meestal vast?", ["Linksom","Rechtsom (clockwise)","Maakt niet uit","Diagonaal"], 1],
    ["Wat is leidingbreuk-detectie?", ["Type isolatie","Een filter","Sensor / systeem dat lekkage signaleert en water afsluit","Soort kraan"], 2],
    ["Wat is een sifon?", ["S-vormige beker onder afvoeren tegen rioolgeur","Pomp","Filter","Klep"], 0],
    ["Welk materiaal is vaak rioolafvoer in modern bouw?", ["Koper","RVS","PVC of PP","Aluminium"], 2],
    ["Welk PBM hoort bij werken op een steiger?", ["Alleen helm","Helm, schoenen, veiligheidsharnas indien open zijde","Niets","Alleen handschoenen"], 1],
    ["Wat is hardsoldeer en zachtsoldeer?", ["Hardsoldeer is voor PVC","Hardsoldeer >450°C; zachtsoldeer <450°C — verschillende toepassingen","Geen verschil","Zachtsoldeer is voor staal"], 1],
    ["Soldeer je open vlam op dit project?", ["Nee, niet zonder een hot-work permit; doorgaans persfittingen i.v.m. lasverbod","Alleen woensdag","Ja, altijd","Alleen 's nachts"], 0],
    ["Wat is een afpersing/druktest?", ["Een schoonmaak","Test waarbij leidingsysteem op druk wordt gebracht om lekkage te controleren","Een meting van temperatuur","Een geluidstest"], 1],
    ["Wat is condensvorming?", ["Een gas","Een schoonmaakmiddel","Vocht dat ontstaat als koud oppervlak in vochtige lucht staat","Een isolatie"], 2],
    ["Wat doe je bij waterlek tijdens werk?", ["Vloer dweilen","Hoofdkraan dichtdraaien, situatie veiligstellen, melden","Doorwerken","Niets"], 1],
    ["Welke leidingen liggen vaak in een leidingschacht?", ["CV, koeling, water, riool, gas (gescheiden)","Alleen riool","Alleen elektra","Niets"], 0],
    ["Wat is een airwasher of luchtbehandelingskast (LBK)?", ["Een ventilator","Toestel dat ventilatielucht conditioneert (filteren, verwarmen, koelen)","Een afzuigkap","Een airco"], 1],
    ["Wat is een radiatorkraan?", ["Soort filter","Sensor","Type pomp","Regelt de waterstroming door een radiator"], 3],
    ["Welke vorm heeft een knel-/klemkoppeling?", ["Recht stuk","T-stuk","Bocht","Conisch sluitende ring met wartelmoer"], 3],
    ["Welke maat sleutel gebruik je voor een 22 mm wartel?", ["8 mm","Ring-/steeksleutel 24 mm of pijptang","30 mm","13 mm"], 1],
    ["Wat is een persfitting versus knelfitting?", ["Pers is demonteerbaar","Knel is permanent","Geen verschil","Persfitting is permanent (perstang); knel is demonteerbaar"], 3],
    ["Wat is een convector?", ["Een sensor","Een soort lamp","Verwarmingstoestel dat lucht via natuurlijke of geforceerde convectie warmt","Een filter"], 2],
    ["Welke isolatie zie je vaak om koudwaterleiding?", ["Gesloten celflexibele isolatie (Armaflex-type) tegen condens","Stof","Glaswol","Geen"], 0],
    ["Wat is een condensafvoer?", ["Afvoer van condenswater uit een airco of LBK","Een ventiel","Vuilwaterafvoer","Hemelwater"], 0],
    ["Wat is een spuiventiel/aftapper?", ["Een meter","Een isolatie","Een sensor","Punt waar je een systeem leegt of doorspoelt"], 3],
    ["Hoe markeer je leidingen na installatie?", ["Niets","Met tape","Met stift","Met genormeerde leidingstickers/kleurringen (medium, richting, druk)"], 3],
    ["Wat doe je met restafval (lood, koper, plastic)?", ["Allemaal in één bak","Mee naar huis","Verbranden","Scheiden in juiste container; koper apart vanwege waarde/recycling"], 3],
    ["Wat is het beste moment om een leiding op druk te zetten?", ["Direct","Aan einde dag","Bij regen","Na visuele controle en afpersing volgens werkinstructie"], 3],
    ["Welke gereedschappen mogen niet gebruikt worden op het project?", ["Pijpsnijder","Steeksleutel","Persgereedschap","Open vlam apparatuur (lasapparaten, brander) zonder vergunning"], 3],
    ["Hoe stem je dagelijks af met de chef-monteur?", ["Alleen via e-mail","Alleen vrijdag","Korte dagstart, taakverdeling, bijzonderheden, einde dag terugkoppeling","Niet"], 2],
    ["Hoe ga je om met een Engelstalige collega-uitvoerder?", ["Negeren","In dialect","Tolkenbureau bellen","Communiceren in helder Engels, gebruik van tekening en pictogrammen"], 3],
  ],

  /* ════════════════════════════════════════════════════════════════════════
     WERKTUIGBOUW — MONTEUR (50 vragen)
     ════════════════════════════════════════════════════════════════════════ */
  'W-monteur': [
    ["Wat is een 4-pijps klimaatsysteem?", ["Aparte aanvoer/retour voor verwarmen én koelen — gelijktijdig mogelijk","Twee leidingen","Eén leiding","Vier waterzuiveringspijpen"], 0],
    ["Wat is een 2-pijps klimaatsysteem?", ["Vier leidingen","Geen leidingen","Eén aanvoer en één retour, óf verwarmen óf koelen","Drie leidingen"], 2],
    ["Welke ISSO-publicatie behandelt CV-installaties woningbouw?", ["ISO 9001","ISSO 51","NEN 3140","NEN 1010"], 1],
    ["Welke ISSO-publicatie behandelt koudeopwekking en distributie?", ["ISSO 30","ISSO 80","ISSO 17","ISSO 75"], 3],
    ["Welk koudemiddel valt onder F-gassen regelgeving?", ["Water (H2O)","HFK's zoals R410A, R32, R134a","Zout","Lucht"], 1],
    ["Wie mag handelingen aan koudemiddelsystemen verrichten?", ["Iedereen","Niemand","Alleen elektrici","Gecertificeerd persoon (F-gassen STEK / vergelijkbaar)"], 3],
    ["Wat is dubbel-pijps klimaatplafond?", ["Plafond met radiator","Plafond met 4 leidingen","Plafond met luchtkanaal","Plafond met aanvoer en retour gekoppeld in 2-pijps systeem"], 3],
    ["Wat is een hydraulische balans bij CV?", ["Pomptesten","Filtering","Drukverlaging","Verdeling van waterstroom zodat elke groep voldoende debiet krijgt"], 3],
    ["Welk apparaat balanceert hydraulisch?", ["Ingrebouwde inregel-/regelafsluiter (bv. Tacosetter, STAD/STAP-V)","Pomp","Reduceerventiel","Filter"], 0],
    ["Wat is een differentiedrukregelaar?", ["Verwarmt water","Stopt water","Houdt het drukverschil over een groep constant","Filtert lucht"], 2],
    ["Welke methode test je een persleiding?", ["Pomp inschakelen","Visueel alleen","Slaan met hamer","Drukbeproeving (afpersing) met juiste medium en duur volgens norm"], 3],
    ["Welke maximale temperatuur tolereert standaard PEX-buis continu?", ["250 °C","20 °C","150 °C","≈ 70-85 °C continu, kortstondig hoger"], 3],
    ["Hoe bepaal je de leidingdiameter voor een verwarmingsgroep?", ["Op gok","Op basis van debiet, drukverlies, snelheid (m/s) en lengte","Altijd 22 mm","Standaard tabel zonder context"], 1],
    ["Welke maximale watersnelheid is gangbaar in distributieleiding?", ["10 m/s","5 m/s","≈ 1,0 m/s om geluid en erosie te beperken","Geen limiet"], 2],
    ["Wat is een driewegventiel?", ["Mengt of verdeelt twee waterstromen voor temperatuurregeling","Een pomp","Een filter","Een ontluchter"], 0],
    ["Wat is een tweewegventiel?", ["Een filter","Open/dicht klep voor één leiding (vaak modulair stuurbaar)","Een verdeler","Een pomp"], 1],
    ["Welke afsluiter is geschikt voor inregeling én afsluiten?", ["Schuif","Vlinderklep alleen","Bolafsluiter alleen","Inregelafsluiter met meetnippels (bv. STAD)"], 3],
    ["Wat is een expansievat?", ["Vat dat volume-uitzetting van het CV-water opvangt","Pomp","Reduceerventiel","Filter"], 0],
    ["Welke voorvuldruk gebruik je voor een typisch CV-expansievat in een woning?", ["Niet relevant","Altijd 5 bar","Statische hoogte (m) / 10 + 0,3 bar (richtlijn)","Altijd 0 bar"], 2],
    ["Wat is een veiligheidsventiel?", ["Pompt","Filtert","Beveiligt installatie tegen overdruk door af te blazen","Mengt"], 2],
    ["Welke koudemiddel-leiding is in de regel groter, zuig- of vloeistofleiding?", ["Zuigleiding is groter (gas, lagere druk/dichtheid)","Gelijk","Geen leiding bestaand","Vloeistof groter"], 0],
    ["Wat is een airless-koeler / dry cooler?", ["Buitenunit die warmte aan buitenlucht afgeeft zonder waterverneveling","Een pomp","Een mengkraan","Een filter"], 0],
    ["Welk medium gebruikt vaak een klimaatplafond met natte koeling?", ["Olie","CO2-direct","Stoom","Gekoeld water (zoutarm, eventueel met glycol)"], 3],
    ["Wat is een 'free cooling' principe?", ["Verwarming aan","Compressor altijd aan","Een type pomp","Buitenlucht/water gebruiken om gebouw te koelen zonder mechanische compressor"], 3],
    ["Wat is een condensaatpomp?", ["Pompt CV-water","Pompt condenswater weg uit airco/LBK naar afvoer","Brandblussysteem","Riool ventilatie"], 1],
    ["Welke isolatieklasse vraagt een koudwaterleiding op vochtige plaats?", ["Gesloten cel (μ ≥ 7000) en juiste dikte tegen condens","Glaswol open","Geen","Tape"], 0],
    ["Wat is een EPB-rapportage?", ["Een lasrapport","Een veiligheidskeuring","Energieprestatieberekening — relevant voor opleveringen","Een prijsopgave"], 2],
    ["Welke MERV/EU-filterklasse hoort bij goede ventilatie kantoren?", ["Geen filter","G2","Tegenwoordig ISO ePM1 / ePM2,5 (was F7-F9)","C0"], 2],
    ["Wat is balansventilatie?", ["WTW: gelijke aan- en afvoerhoeveelheden, met warmteterugwinning","Alleen toevoer","Geen ventilatie","Alleen afvoer"], 0],
    ["Wat is WTW?", ["Warmte-TerugWinning uit ventilatieretour","Water-TochtWisselaar","Wattmetergroep","Geen afkorting"], 0],
    ["Welke stappen horen bij inbedrijfstelling klimaatplafond?", ["Spoelen, ontluchten, drukproef, inregelen, meet- en regeltechniek inregelen","Direct aanzetten","Alleen visuele controle","Niets specifieks"], 0],
    ["Wat is een Nutsleiding (gas/elektra/water)?", ["Aansluiting van openbare voorziening tot meterkast","Privéleiding","Riool","Dakleiding"], 0],
    ["Wat is een geleidingsbeugel/-clip voor leidingen?", ["Bevestiging die thermische beweging toelaat","Filter","Afsluiter","Pomp"], 0],
    ["Hoe bevestig je leiding aan houten ondergrond op dit project?", ["Spijkeren","Lijmen","Met geschikte schroef-/clipsysteem (geen lasconstructies)","Lassen"], 2],
    ["Welke watertemperatuur is gangbaar voor klimaatplafond koelen?", ["6 °C aanvoer","45 °C aanvoer","Aanvoer 14-16 °C, retour 16-18 °C, boven dauwpunt","30 °C aanvoer"], 2],
    ["Wat is dauwpuntregeling?", ["Een veiligheidsventiel","Een akoestische afdichting","Voorkomen dat watertemperatuur onder dauwpunt komt om condens te voorkomen","Een filter"], 2],
    ["Wat is een drukvat (CV)?", ["Synoniem voor expansievat met membraan","Een tank voor warm water","Een afsluiter","Een opslagtank"], 0],
    ["Welk meetinstrument meet luchtdebiet?", ["Voltmeter","Multimeter","Thermohygrometer","Hittedraad-/vleugelrad anemometer of debietmeetkruis"], 3],
    ["Welke warmtemeter gebruik je voor afrekenmeting?", ["Voltmeter","MID-gecertificeerde warmtemeter (debiet + ΔT)","Drukmeter","Watermeter"], 1],
    ["Wat is een 'low-loss header' / open verdeler?", ["Filter","Brandklep","Hydraulische ontkoppeling tussen primair en secundair circuit","Sensor"], 2],
    ["Wat is BIM en hoe gebruik je het?", ["Excel","Een schroef","Building Information Modeling — 3D-model + data, voor coördinatie en uitvoering","Een meetapparaat"], 2],
    ["Welke geluidseisen gelden in monumentale ruimten op dit project?", ["Geen eisen","Strenge eisen — installaties zo stil mogelijk; isolatie en demping","Alleen 's nachts","Hoogste lawaai toegestaan"], 1],
    ["Wat is een zelfregelende thermostaatkraan?", ["Pomp","Filter","Radiatorkraan die ruimtetemperatuur per ruimte regelt","Sensor"], 2],
    ["Welke procedure volg je bij een lekkage in monumentale ruimte?", ["Direct afsluiten, opvang voorzien, monumentenzorg/uitvoerder informeren","Hopen op droging","Negeren","Doorwerken"], 0],
    ["Wat is een afblaasleiding op een veiligheidsventiel?", ["Een filterleiding","Geleide afvoer van water bij afblazen, naar zichtbare punt","Een retourleiding","Een ventilatie"], 1],
    ["Wat is een persdruk-test bij gas?", ["Met water","Met perslucht","Doe je zelf","Mag NIET door W-monteur zonder erkenning — alleen erkend installateur"], 3],
    ["Welke afsluiter scheidt twee gebouwgedeelten in renovatie?", ["Brandklep","Geen","Filter","Sectie-afsluiters in centraal verdeelpunt"], 3],
    ["Wat is een vorstbeveiliging?", ["Filter","Pomp","Regeling die installatie beschermt tegen bevriezing","Een afsluiter"], 2],
    ["Welke documentatie hoort bij oplevering W?", ["Niet vereist","Foto's via WhatsApp","O&M-handboek, asbuilt, drukrapport, inregelrapport, certificaten","Alleen factuur"], 2],
    ["Hoe stem je af met de E-monteur over een klimaatplafond?", ["Niet","Pas bij oplevering","Eigen plan","Sensor- en aansluitingen W coördineren met regeltechniek E (KNX/MOD-bus)"], 3],
  ],

  /* ════════════════════════════════════════════════════════════════════════
     WERKTUIGBOUW — CHEF-MONTEUR (50 vragen)
     ════════════════════════════════════════════════════════════════════════ */
  'W-chef': [
    ["Wat is jouw rol bij inbedrijfstelling klimaatplafond?", ["Alleen kijken","Coördinatie spoeling, drukproef, inregeling, MR-test, oplevering","Geen rol","Eigen werk"], 1],
    ["Welke ISSO-richtlijn voor inregelen hydraulisch evenwicht ken je?", ["ISSO 50/57 (CV/koel) en publicaties hydraulisch inregelen","NEN 1010","NEN 3140","ISO 27001"], 0],
    ["Welke verantwoordelijkheid heb je voor F-gassen op je ploeg?", ["Toezien op gecertificeerd personeel; logboek bijhouden","Geen","Geen logboek nodig","Alleen administratie"], 0],
    ["Welk planningsdocument coördineer je dagelijks?", ["Niets","Werkpakketten per ruimte, materiaalstroom, raakvlakken E/W/B","Alleen weekplanning","Alleen einddatum"], 1],
    ["Welke risico's check je vooraf in monumentale ruimten?", ["Geen","Alleen kosten","Alleen tijd","Brandrisico, schade gevoelig materiaal, stof, monumentenzorg-eisen"], 3],
    ["Wat is een coördinatietekening?", ["Een schets","Tekening die E, W, B in één laagsysteem afstemt — voorkomt kruisingen","Tekstverklaring","Een factuur"], 1],
    ["Welke data borg je voor as-built?", ["Alleen oude tekening","Alleen einde","Wijzigingen tijdens uitvoering tijdig in BIM/AutoCAD verwerken","Niets"], 2],
    ["Wat doe je als drukproef faalt?", ["Doorgaan","Druk verlagen","Negeren","Stoppen, lokaliseren, herstellen volgens procedure, hertesten + rapporteren"], 3],
    ["Welke kwaliteitsborging op klimaatplafond pas je toe?", ["Spoelprotocol, druktest, debietmeting, oplevercertificaat per zone","Geen","Visueel alleen","Steekproef per maand"], 0],
    ["Welke MR-eisen ken je (Meet- & Regeltechniek)?", ["Geen","Alleen alarm","Aanvoer-, retour-, ruimtevoelers; klepposities; alarmen; logging","Alleen aanvoer"], 2],
    ["Wat is een functietest?", ["Test waarbij regelingen, beveiligingen, alarmen op werking worden gevalideerd","Spoeling","Visueel","Druktest"], 0],
    ["Welke Eurovent-/SCOP-/EER-cijfers gebruik je voor koeling?", ["Niet relevant","Tarief","Energie-efficiency koel/verwarm onder genormeerde condities","Brandklasse"], 2],
    ["Welke wettelijke eisen gelden voor stookinstallaties?", ["Geen","SCIOS Scope 1/2/4 keuringen + Activiteitenbesluit","ISO 9001 alleen","Alleen NEN 1010"], 1],
    ["Welk lucht-/water debiet bewaak je tijdens commissioning?", ["Geen","Alleen totaal","Per zone gemeten en vergeleken met ontwerpwaarde, afwijking <±10%","Alleen op piek"], 2],
    ["Wat is een tekortkomingenlijst (snagging)?", ["Een schroefset","Lijst openstaande punten ná oplevering te herstellen","Een softwarepakket","Een loonstrook"], 1],
    ["Wat is een bouwlogistiekplan?", ["Een softwareplan","Pauzeplan","Brandwachtplan","Plan voor materiaalaanvoer, opslag, afvoer in en rondom de bouwplaats"], 3],
    ["Welke informatie deel je elke ochtend met je ploeg?", ["Doelen vandaag, veiligheid, samenwerking E/W, materiaalpunten","Niets","Alleen plek","Alleen tijden"], 0],
    ["Welke verantwoordelijkheid heb je bij hot-work in een gebouw met lasverbod?", ["Alleen 's nachts","Soms toestaan","Geen open vlam toestaan; alternatieven (pers/koppelingen) borgen","Bij regen ja"], 2],
    ["Hoe stem je af met de hoofdaannemer (CWD)?", ["Wekelijkse coördinatie, dagelijks korte updates, structuur in afwijkingen","Niet","Random","Maandelijks"], 0],
    ["Welke eisen aan opleidingen monteurs op dit Den Haag-project?", ["VCA, vakdiploma, F-gassen indien koudemiddel; periodieke bijscholing","Geen","Alleen taal","Alleen rijbewijs"], 0],
    ["Wat is een proefbedrijf (commissioning)?", ["Een offerte","Een hoekijzer","Periode waarin installatie onder gebruik condities wordt getest","Een meetinstrument"], 2],
    ["Wat doe je bij asbestverdacht materiaal?", ["Direct stoppen, ploeg veiligstellen, gespecialiseerd bedrijf laten saneren","Voorzichtig doorgaan","Maskertje opzetten","Aanstampen"], 0],
    ["Welke stappen volg je bij contamination-risico in waterleiding?", ["Niets","Cola erdoor","Spoelprotocol per ISSO 55-1, microbiologische monsters indien vereist","Alleen visueel"], 2],
    ["Welke metingen rapporteer je bij hydraulisch inregelen?", ["Alleen temperatuur","Debiet, drukverlies per zone, autoriteit, instelwaarden — gedocumenteerd","Alleen pomp","Geen"], 1],
    ["Wat is een autoriteit van een regelafsluiter?", ["Een rang","Verhouding kleerkverlies tot totaal kringverlies (richtlijn ≥ 0,3)","Geen begrip","Een drukklasse"], 1],
    ["Hoe bewaak je voortgang met meerdere ploegen op 7 gebouwen?", ["Faseplanning, mijlpalen, wekelijkse review, dashboards en LMRA's","Spreadsheet zonder review","Op gevoel","Niets"], 0],
    ["Welke documentatie eis je bij prefab-leverancier?", ["Foto via mail","Niets","Tekeningen, materiaalcertificaten, drukproefcertificaten, identificatie","Alleen factuur"], 2],
    ["Wat is een vergrendel-/markeerprocedure (LOTO) bij W-werk?", ["Alleen E-elektra","Niet nodig","Pomp/ketel uit, afsluiters dicht en gelabeld, energiebronnen geborgd","Alleen bij gas"], 2],
    ["Wat is je rol bij een veiligheidsincident in jouw ploeg?", ["Eerste hulp, situatie veilig stellen, melden, oorzaak en preventie","Achteraf bedenken","Toedekken","Alleen gevallen melden"], 0],
    ["Welke kennis verwacht je van een W-monteur over geluidsoverdracht?", ["Geen","Pomp/leidingvibratie isoleren, demper, juiste bevestiging","Alleen technisch interessant","Alleen visueel"], 1],
    ["Wat is je strategie als ontwerp en uitvoerbaarheid afwijken?", ["Issue loggen, voorstel maken, met engineer/uitvoerder afstemmen, RFI sturen","Negeren","Alleen melden achteraf","Zelf veranderen"], 0],
    ["Wat is een RFI?", ["Request For Information — formele vraag aan ontwerpteam","Een meting","Een ventiel","Een type kraan"], 0],
    ["Hoe stem je raakvlak elektra-W op klimaatplafond af?", ["Pas op de dag","Alleen visueel","Niet","Sensoren, kleppen, regelaars en bekabeling integraal plannen met E-chef"], 3],
    ["Wat zijn voor jou kritieke inbedrijfstellingstesten?", ["Drukproef, spoeling, debiet, temperatuur, regeling, alarmen","Geen","Alleen drukproef","Alleen temperatuur"], 0],
    ["Welke milieueisen gelden bij koudemiddel-werk?", ["Alleen kosten","Alleen tijd","Geen","GWP-bewust werken, lekdetectie, juiste recovery, registratie F-gassen"], 3],
    ["Welke informatie staat in een testcertificaat?", ["Niets","Beproevingsmedium, druk, duur, resultaat, datum, paraaf","Alleen prijs","Alleen tekst"], 1],
    ["Wat is een sequentieregeling op klimaatplafonds?", ["Cascade-/sequence-regeling tussen verwarmen, neutrale band en koelen","Constant uit","Constant aan","Random"], 0],
    ["Welke risico's heb je bij een renovatie met blijvende gebruikers (blijvend gebruik)?", ["Geluid/stof, brandveiligheid, vluchtwegen, beveiliging, beeldvorming","Geen","Alleen kosten","Alleen tijd"], 0],
    ["Welke escalatieroute volg je bij stagnatie?", ["Niet escaleren","Direct directie","Naar opdrachtgever","Eerst uitvoerder, dan hoofduitvoerder, vervolgens projectmanager"], 3],
    ["Hoe coach je een hulpmonteur die fouten maakt?", ["Veilige feedback, voordoen, korte cyclus, geleidelijk meer verantwoordelijkheid","Wegsturen","Strafrooster","Negeren"], 0],
    ["Wat is je beleid voor PBM-controle?", ["Niets","Eens per maand","Visueel iedere ochtend, schoonzijn, juiste maat en NEN-keuring waar vereist","Bij klacht"], 2],
    ["Wat is je rol bij sub-aannemers (bijv. isolatieploeg)?", ["Alleen einde","Plannen, controleren werkwijze, kwaliteitscheck, raakvlakken","Alleen factuur","Niets"], 1],
    ["Welke documentatie geef je af bij eindoplevering?", ["Alleen factuur","Asbuilt, O&M, certificaten, inregelrapporten, garanties, restpuntenlijst","Niets","Mondeling"], 1],
    ["Wat is een commissioning manager (CxM)?", ["Een softwarepakket","Een kraan","Onafhankelijke rol die hele commissioningsproces coördineert","Een soort meter"], 2],
    ["Wat is je strategie voor hete dagen tijdens uitvoering?", ["Pauze schrappen","Hardere tempo","Niet","Werktijden aanpassen, water, schaduw, signalering hittebelasting"], 3],
    ["Welke registratie houd je per gebouw bij?", ["Logboek met voortgang, afwijkingen, beslissingen, foto's","Alleen totaal","Eind project","Niet"], 0],
    ["Hoe meet je succes van jouw uitvoering?", ["Veiligheid, kwaliteit, planning, klanttevredenheid, leerpunten","Alleen kwaliteit","Alleen kosten","Alleen tijd"], 0],
    ["Wat is een 'snagging-walk'?", ["Een trainingstype","Een wandeling","Inspectieronde net vóór oplevering om resterende punten te benoemen","Een meting"], 2],
    ["Welke samenwerking met BHV is voor jou belangrijk?", ["Alleen rookmelder","Vluchtwegen vrij, brandklepposities, brandvergunning, gebruikersinformatie","Pas bij brand","Niet"], 1],
    ["Wat is jouw rol als chef-monteur bij verbeterprojecten (lessons learned)?", ["Alleen vergaderen","Vergeten","Leerpunten vastleggen, delen met team en bedrijf, structureel verbeteren","Niets"], 2],
  ],

};

/* ============================================================================
   FOTOHERKENNINGSVRAGEN — 2 random getrokken per testsessie
   Format:  { vraag, img, opties:[A,B,C,D], correct: 0-3 }
   ============================================================================ */
const IMAGE_QUESTIONS = {
  'E-hulpmonteur': [
    { vraag: "Welk component zie je op de afbeelding?", img: "images/img_E-hulpmonteur_1.png", opties: ["Stopcontact","Installatieautomaat","Lasdoos","Dimmer"], correct: 1 },
    { vraag: "Welk onderdeel wordt hier afgebeeld?", img: "images/img_E-hulpmonteur_2.jpeg", opties: ["Aarddraad","Wandschakelaar","Kabelgoot","Hoofdschakelaar"], correct: 1 },
    { vraag: "Welke elektrotechnische component zie je?", img: "images/img_E-hulpmonteur_3.jpeg", opties: ["Groepenkast","Stekker","Transformator","Bewegingssensor"], correct: 0 },
  ],
  'E-monteur': [
    // GEEN correct antwoord gedefinieerd — overgeslagen: Welk component zie je op de afbeelding?
    { vraag: "Welk component zie je op de afbeelding?", img: "images/img_E-monteur_2.jpeg", opties: ["Relais","Magneetschakelaar","Eindgroep","Aardrail"], correct: 2 },
    { vraag: "Welk component zie je op de afbeelding?", img: "images/img_E-monteur_3.png", opties: ["Hoofdschakelaar","Installatieautomaat","Smeltzekering","Aardlekschakelaar"], correct: 0 },
  ],
  'E-chef': [
    { vraag: "Welk component zie je op de afbeelding?", img: "images/img_E-chef_1.png", opties: ["Frequentieregelaar","Vermogensautomaat","Magneetschakelaar","Softstarter"], correct: 1 },
    { vraag: "Welk component zie je op de afbeelding?", img: "images/img_E-chef_2.png", opties: ["Aardlekautomaat","Motorbeveiligingsschakelaar","Vermogensautomaat","Relais"], correct: 1 },
    { vraag: "Welk industrieel component zie je op de afbeelding?", img: "images/img_E-chef_3.png", opties: ["PLC-module","Installatieautomaat","Transformator","Tijdrelais"], correct: 0 },
  ],
  'W-hulpmonteur': [
    { vraag: "Welke fitting wordt hier afgebeeld?", img: "images/img_W-hulpmonteur_1.jpeg", opties: ["Perskoppeling","Sokverbinding","Kniekoppeling","Flensverbinding"], correct: 0 },
    { vraag: "Welk onderdeel zie je op de afbeelding?", img: "images/img_W-hulpmonteur_2.jpeg", opties: ["Kogelkraan","T-stuk","Flexibele slang","Radiatorkraan"], correct: 0 },
    { vraag: "Welke verbinding wordt hier toegepast?", img: "images/img_W-hulpmonteur_3.jpeg", opties: ["Flensverbinding","Knelkoppelingen","Persverbinding","Soldeerverbinding"], correct: 1 },
  ],
  'W-monteur': [
    { vraag: "Welke fitting wordt hier afgebeeld?", img: "images/img_W-monteur_1.png", opties: ["Perskoppeling","Sokverbinding","Kniekoppeling","Verloopring"], correct: 3 },
    { vraag: "Welk appendage zie je op de afbeelding?", img: "images/img_W-monteur_2.jpeg", opties: ["Inregelafsluiter","Terugslagklep","Veiligheidsventiel","Kogelkraan"], correct: 0 },
    { vraag: "Welk component hoort bij deze leidinginstallatie?", img: "images/img_W-monteur_3.jpeg", opties: ["Expansievat","Warmtewisselaar","Circulatiepomp","Drukregelaar"], correct: 2 },
  ],
  'W-chef': [
    { vraag: "Welke industriële verbinding wordt hier afgebeeld?", img: "images/img_W-chef_1.jpeg", opties: ["Victaulic koppeling","Flensverbinding","Persverbinding","Soldeerverbinding"], correct: 1 },
    { vraag: "Welke installatiecomponent wordt hier toegepast voor drukregeling?", img: "images/img_W-chef_2.jpeg", opties: ["Expansievat","Reduceerventiel","Veiligheidsventiel","Circulatiepomp"], correct: 1 },
  ],
};
