/* ============================================================================
   MAINTEC SKILLS TEST — QUESTION BANK (ENGLISH)
   ----------------------------------------------------------------------------
   Format per question:  [question_text, [option_A, option_B, option_C, option_D], correctIndex]
   correctIndex: 0 = A, 1 = B, 2 = C, 3 = D
   50 questions per profile × 6 profiles = 300 questions total.
   Random selection of 15 questions per test session.
   ============================================================================ */

const QUESTIONS_EN = {

  /* ════════════════════════════════════════════════════════════════════════
     ELECTRICAL — ASSISTANT FITTER (50 questions, basic level)
     ════════════════════════════════════════════════════════════════════════ */
  'E-hulpmonteur': [
    ["What colour is the protective earth (PE) in a Dutch electrical installation?", ["Brown","Blue","Black","Yellow/green"], 3],
    ["What voltage does a standard wall socket use in the Netherlands?", ["24 Volts","400 Volts","230 Volts","110 Volts"], 2],
    ["What is ALWAYS the first action before working on an electrical installation?", ["Put on gloves","Grab the multimeter","Warn a colleague","De-energise, lock-out and verify absence of voltage (LOTO)"], 3],
    ["Which tool do you use to remove cable insulation?", ["Combination pliers","Hammer","Wire stripper","Screwdriver"], 2],
    ["What does the IP-rating on electrical equipment mean (e.g. IP44)?", ["Power class","Cable cross-section","Voltage class","Degree of protection against contact, dust and water"], 3],
    ["Which type of cable is used for fixed in-wall installation?", ["Extension cord","UTP cable","H07RN-F","VMVK (NYM)"], 3],
    ["What colour is a neutral conductor (N)?", ["Brown","Yellow/green","Blue","Black"], 2],
    ["What colour is the live conductor in a modern installation?", ["Yellow/green","White","Brown (or black/grey in 3-phase)","Blue"], 2],
    ["What is the function of a residual current device (RCD)?", ["Protect against earth-leakage currents to prevent electrocution","Switch lighting","Protect against overcurrent","Voltage regulator"], 0],
    ["How do you check whether a wire is live?", ["By smelling it","By colour","With a voltage tester or multimeter","By touching it"], 2],
    ["What must you wear when working on a construction site?", ["Trainers","Just work clothing","Hearing protection only","Safety helmet, S3 safety boots and high-visibility clothing"], 3],
    ["What is a voltage detector pen?", ["A measuring tape","Type of fuse","Type of screwdriver","A small device that indicates whether a conductor is live"], 3],
    ["What is the maximum power on a 16A circuit at 230V?", ["7360 W","1600 W","3680 W","16 W"], 2],
    ["What is the best way to pull a cable through an empty conduit?", ["By hand only","With unprotected compressed air","With a screwdriver","With a draw-spring (fish tape) and possibly cable lubricant"], 3],
    ["What is the standard mounting height of a wall socket in a living area?", ["Approx. 30 cm above the finished floor","Approx. 100 cm","Approx. 5 cm","Approx. 180 cm"], 0],
    ["Which tool do you use to drill holes in concrete for conduit?", ["Pliers","SDS rotary hammer / impact drill","Jigsaw","Wood drill"], 1],
    ["What do you do if you find damaged tools?", ["Keep using until end of day","Pass to a colleague","Quickly repair yourself","Take out of service immediately, report and have them inspected"], 3],
    ["What is a Wago lever connector?", ["Type of fuse","A measuring instrument","A push-in connector for joining conductors without screws","Type of switch"], 2],
    ["What is the difference between flush-mount and surface-mount fittings?", ["No difference","Surface-mount has higher voltage","Flush-mount is for outdoors","Flush-mount sits inside the wall, surface-mount sits on top"], 3],
    ["A TOTAL WELDING BAN applies on this project. How then do you fix cable trays to the structure?", ["With screw/bolt connections or clamping systems","With TIG welding","With MIG welding","With thermite"], 0],
    ["Why is there a welding ban on this project?", ["The buildings have wooden floors — fire risk","Welding is too expensive","Welding fumes are forbidden","No suitable welding equipment available"], 0],
    ["What do you do before drilling a hole through a wall?", ["Check the location of pipes/wires with detection","Use a smaller drill","Ask a colleague to watch","Drill straight away"], 0],
    ["What is the minimum conductor cross-section for a lighting circuit?", ["0.75 mm²","6 mm²","0.5 mm²","1.5 mm²"], 3],
    ["What is the minimum conductor cross-section for a 16A wall-socket circuit?", ["0.75 mm²","10 mm²","2.5 mm²","1.5 mm²"], 2],
    ["What is a junction box?", ["Type of multi-socket","A box where conductors are connected together","Type of fuse","Power source"], 1],
    ["What do you do with waste (cable scraps, packaging) on the construction site?", ["In the waste bin","Leave it","Sort it and put in the correct waste container","Take it home"], 2],
    ["What is a DALI system?", ["A switch","Type of fuse","Type of cable","A protocol for digital lighting control"], 3],
    ["Which symbol on a drawing represents a wall socket?", ["Triangle","Square with a diagonal","Circle with radial lines","Cross"], 2],
    ["What is the purpose of a conduit?", ["Wall reinforcement","Water pipe","Mechanical protection of cables and ability to replace them later","Ventilation"], 2],
    ["How do you connect a single-pole switch to a lamp?", ["Live via the switch to the lamp, neutral direct to the lamp","Neutral via switch","Both via switch","Earth via switch"], 0],
    ["What is a PIR motion detector?", ["Socket with sensor","Sensor that detects motion to switch lighting","Smoke detector","Type of fuse"], 1],
    ["What do you do when you spot an unsafe situation?", ["Stop, secure the area and immediately report to the supervisor","Nothing — that's someone else's task","Solve it yourself","Keep working until break"], 0],
    ["How do you communicate with an English-speaking supervisor colleague?", ["In clear English, using drawings or gestures when in doubt","Ignore","Only in Dutch","Via WhatsApp text translator while working"], 0],
    ["What is the difference between Class I and Class II appliances?", ["Class I uses 110V","No difference","Class I requires earthing, Class II is double-insulated","Class II is for industry"], 2],
    ["When do you use a safety harness?", ["Always","Never","When working at heights > 2.5 m without other edge protection","Only on the ground floor"], 2],
    ["What must you do before using a ladder?", ["Climb straight away","Jump on top of the ladder","Stand on the top rung","Visual inspection, correct angle (75°), set up stably"], 3],
    ["Which cable may you NOT use for permanent fixed installation?", ["NYM (VMVK)","H05VV-F (extension-cord grade)","XGB","NYAF inside a conduit"], 1],
    ["What is a conduit?", ["A tube in which electrical conductors are installed","Type of socket","Type of cable","Type of lamp holder"], 0],
    ["What is a switch-fitting set?", ["Type of cable","Combination of back box, mechanism and cover frame","Power supply box","Junction box with cover"], 1],
    ["In a heritage building (Building J) — how do you install new wiring?", ["Drill where you like","Break open all walls","Run along the outside facade","As invisibly as possible, respecting heritage value, in consultation"], 3],
    ["What information is on a cable reel/drum?", ["Only weight","Only colour","Type, cross-section, length, manufacturer","Only price"], 2],
    ["What is a cable clip?", ["Cutting tool","Type of connector","Fastener to neatly attach a cable to a surface","Marker label"], 2],
    ["What is the typical minimum bend radius of an installation cable?", ["2× cable diameter","Doesn't matter","As tight as possible","Approx. 6× cable diameter"], 3],
    ["What PPE is the minimum for working in a switchboard?", ["Just shoes","Safety glasses, insulating gloves where needed","Just helmet","None"], 1],
    ["What do you do with rejected electrical equipment / cords?", ["Use a bit longer","Dispose separately, do not put back into use","Resell","Repair with tape"], 1],
    ["What is equipotential bonding?", ["Current distribution","Connecting metal parts to earth to prevent voltage differences","A wired safety lock","Voltage regulation"], 1],
    ["How do you handle waste on the work floor at the end of the day?", ["In an open fire","Leave it","Put it in the corridor","Tidy up the workplace, sort and dispose of waste"], 3],
    ["What do you do if you have lost a tool or material?", ["Keep quiet","Replace it yourself","Report to the lead fitter or supervisor","Take someone else's"], 2],
    ["What is the purpose of toolbox meetings?", ["Performance review","Short safety and work briefing before the work starts","Social moments","Break"], 1],
    ["What do you do if power unexpectedly fails during work?", ["Just keep working","Reset the main switch yourself","Take a break","Stop work, check the situation and inform the lead fitter"], 3],
  ],

  /* ════════════════════════════════════════════════════════════════════════
     ELECTRICAL — FITTER (50 questions, trade level)
     ════════════════════════════════════════════════════════════════════════ */
  'E-monteur': [
    ["Which standard governs low-voltage electrical installations in the Netherlands?", ["NEN 1006","NEN 3140","NEN 50110","NEN 1010"], 3],
    ["Which standard governs SAFE work on and with electrical installations?", ["NEN 1010","NEN 2535","ISO 9001","NEN 3140"], 3],
    ["What is the maximum loop impedance (Zs) at which a 16A B-curve breaker disconnects within 0.4 s?", ["≈ 2.87 Ω","Unlimited","≈ 0.2 Ω","≈ 23 Ω"], 0],
    ["At which leakage current must a Type A RCD disconnect at the latest?", ["30 mA within 300 ms","500 mA","1 A","100 mA"], 0],
    ["Which instrument do you use for insulation resistance measurement?", ["Frequency meter","Megger (insulation resistance tester)","Voltmeter","Clamp meter"], 1],
    ["What is the minimum insulation resistance at 500 V test voltage on a new installation per NEN 1010?", ["≥ 1 MΩ","≥ 100 Ω","≥ 1 kΩ","≥ 1 GΩ"], 0],
    ["What is the requirement for earth resistance in a TT system?", ["RA × IΔn ≤ 50 V (in practice usually Ra ≤ 167 Ω at 30 mA)","Doesn't matter","Always < 1 Ω","< 1000 Ω"], 0],
    ["What is selectivity in an installation?", ["All breakers trip simultaneously","Nothing trips","Only the main connection","On a fault, only the closest protective device disconnects"], 3],
    ["Which protective device protects against both overcurrent AND short circuit?", ["Magnetic contactor","Filter","RCD","Miniature circuit breaker (MCB)"], 3],
    ["What is the difference between B, C and D characteristics?", ["Different price","Different tripping current (3-5×, 5-10×, 10-20× In)","Different colour","Different voltage"], 1],
    ["How many conductor groups does a TN-S system have?", ["Only L and PE","Combined PEN","2 phases, 1 N","L, N and a separate PE conductor"], 3],
    ["Which instrument do you use to check the continuity of a PE conductor?", ["Frequency meter","Wattmeter","Low-ohm meter (PE continuity tester)","Voltmeter"], 2],
    ["What is the most important inspection document after handover of a new installation?", ["Delivery note","Email confirmation","Inspection report per NEN 1010 / NTA 8220 with measured values","Drawing"], 2],
    ["Which cable do you use for fire-resistant installations (e.g. emergency lighting)?", ["Function-retention cable (e.g. (N)HXH FE180/E30)","Standard NYM","Coax","H05VV-F"], 0],
    ["How is a 3-phase supply designated?", ["Plus and minus","L1, L2, L3 + N + PE","A, B, C","R, S, T + 0"], 1],
    ["What is the voltage between two phases in a 400/230V network?", ["≈ 690 V","≈ 230 V","≈ 400 V","≈ 110 V"], 2],
    ["How do you correctly connect a 3-phase wall socket (CEE 16/5)?", ["Order doesn't matter","Only 3 phases, no N or PE","L1, L2, L3, N, PE per the IEC 60309 wiring scheme","Earth first while energising"], 2],
    ["What is a kWh meter?", ["Frequency meter","Voltmeter","Earth resistance meter","Meter that records electrical energy"], 3],
    ["Which type of cable do you use for underground installation?", ["YMvKas or XMvK (ground cable)","NYAF","NYM","H07RN-F"], 0],
    ["What is a PEN conductor?", ["Plus conductor","Combined neutral and earth conductor in a TN-C system","Earth only","Neutral only"], 1],
    ["What is the maximum voltage drop across a final circuit per NEN 1010 (guideline)?", ["20%","10%","No limit","3% for lighting / 5% for other"], 3],
    ["What do you do if the measured Re (earth resistance) is too high?", ["Ignore","Add more RCDs","Extend the earth electrode or add another, re-measure","Fit a smaller fuse"], 2],
    ["What is the LOTO principle?", ["A drawing software","A switching sequence","Lock-Out / Tag-Out: locking and labelling energy sources","Type of cable"], 2],
    ["What is the difference between active and reactive power?", ["Reactive is loss in the cable","Active (W) does work; reactive (var) builds magnetic fields","Active is only DC","No difference"], 1],
    ["What is THD (Total Harmonic Distortion)?", ["Type of switch","Measure of harmonic distortion on a network","Type of power","A heat measurement"], 1],
    ["The symbol ⊕ on a drawing can stand for what type of motor?", ["Circle with S","Circle with R","Circle with T","Circle with M"], 3],
    ["What is the preference for routing CAT6 data and power?", ["All together","Only via the same cable","Doesn't matter","Separate trays / minimum parallel distance to avoid EMC interference"], 3],
    ["What is a NEN 3140 inspection?", ["One-off new-build inspection","An exam","A software version","Periodic inspection of electrical work equipment and installations"], 3],
    ["Which equipment is required to be H&S-certified for electrical work?", ["Personal electrical tools and measuring instruments (annually or per supplier)","Screwdriver without test tip","Hammer","None"], 0],
    ["What is the typical switching sequence when commissioning a distribution board?", ["Highest first","Main switch → RCD → MCBs from low to high power","Not relevant","Random"], 1],
    ["How do you fix an unbalanced load in 3-phase?", ["Bigger fuse","Redistribute heavy loads across the phases","Extra N conductor","Nothing — the breaker fixes it"], 1],
    ["What is a busbar?", ["Power rail (conductive strip) in a distribution unit","Type of pipe","Type of cable","Type of welding device"], 0],
    ["What is the maximum continuous load of a C16 breaker?", ["16 A","160 A","32 A","8 A"], 0],
    ["What is a function-retention installation?", ["A fibre network","UPS","An installation that keeps working for a defined time during a fire (e.g. 30/60/90 min)","Improved insulation"], 2],
    ["What is the difference between centrally monitored and self-contained emergency lighting?", ["No difference","Self-contained is forbidden","Monitored is centrally supervised; self-contained is autonomous (own battery)","Monitored is more expensive and standard"], 2],
    ["Which protection class does a double-insulated appliance have?", ["Class I","Class IV","Class II (square in square)","Class III"], 2],
    ["What is a KNX system?", ["Type of cable","Open bus protocol for building automation","Type of fuse","A free application"], 1],
    ["How do you measure power factor (cos φ)?", ["With a regular voltmeter","With a multimeter Ω-mode","With just a clamp meter","With a power quality analyser"], 3],
    ["Which earth do you use for a touch-sensitive metal washbasin in a wet area?", ["Only N","Own earth rod","Connect to the local equipotential bonding","No earth needed"], 2],
    ["What is a SELV circuit?", ["A 400V circuit","Safety extra-low voltage, separated from the mains (≤ 50 V AC)","A high-voltage circuit","A 230V circuit"], 1],
    ["How do you mark a circuit that has been switched off?", ["Don't mark it","With a lockout lock and label (LOTO) and then verify dead","With a marker","With tape"], 1],
    ["How do you handle suspected asbestos material in older buildings?", ["Wrap it and continue","Continue with a mask","Remove it yourself","Stop work, report to the supervisor, engage a specialist team"], 3],
    ["What is a trench cover and when do you use it?", ["A type of insulating tape","A type of cable","To protect open cable/conduit trenches, placed before backfilling","A safety helmet"], 2],
    ["What must you check on a new wall socket before commissioning?", ["Polarity, earthing, voltage and adequate clamping force; visual + measurement","Only voltage","Only colour","Nothing"], 0],
    ["What is a loop impedance measurement (Zs)?", ["Measurement of phase-PE impedance to validate the disconnection condition","Light intensity measurement","Voltage measurement only","Earth-resistance measurement only"], 0],
    ["How do you approach work in a heritage building (e.g. Building J)?", ["Drill where you want","Survey, avoid irreversible interventions, agree solutions with heritage authority","Demolish where needed","Work fast without permission"], 1],
    ["What is a PE-S installation concept?", ["A measuring device","A type of supply","A type of switch","A TN-S system with a separate PE conductor — preferred for modern installations"], 3],
    ["What do you do if your measurements deviate from the standard?", ["Continue","Ignore","Use a different meter","Stop, investigate the cause, repair and re-measure — record"], 3],
    ["Which document do you hand over to the client at handover?", ["Only the drawing","Only the invoice","Inspection report, as-built drawings and user manual","Nothing"], 2],
    ["How do you align daily with an English-speaking supervisor?", ["Only via WhatsApp","Don't","With a per-hour interpreter","Short morning briefing in English, with drawings and checklists, and clear agreements"], 3],
  ],

  /* ════════════════════════════════════════════════════════════════════════
     ELECTRICAL — LEAD FITTER (50 questions, leadership & advanced)
     ════════════════════════════════════════════════════════════════════════ */
  'E-chef': [
    ["What responsibility does a lead fitter have under NEN 3140?", ["Only administration","No statutory role","Designation as 'Trade-Competent Person' (VP), with mandate for specific work","Only supervision"], 2],
    ["Who is responsible for the work preparation of his crew on site?", ["The assistant fitter","The lead fitter, in coordination with the supervisor and main supervisor","Costing department","The client"], 1],
    ["What do you do before a crew starts in a new room on this project?", ["Start straight away","LMRA and toolbox, review RI&E, task division, checks for pipes/asbestos/heritage","Order materials later","Break"], 1],
    ["What risks do you identify in a heritage building (Building J)?", ["Only cost risk","Damage to monumental elements, fire risk, dust in public areas","Only time","None"], 1],
    ["What is an LMRA?", ["A measurement","A reporting form","A type of cable","Last Minute Risk Analysis just before the start of a task"], 3],
    ["How do you arrange leadership with foreign-language supervisor colleagues?", ["Hire an interpreter per hour","Clear visual work instructions + English daily briefing + daily alignment","Don't communicate","All by email"], 1],
    ["How do you check the quality of your crew's work?", ["Only complaint-driven","Once at the end","Periodic spot checks, handover checks, recording deviations, feedback","Trust is enough"], 2],
    ["Which selectivity has priority in a hospital-like critical installation?", ["Time-delay on all breakers","Full selectivity (only the lowest disconnects) even on short circuit","No selectivity","All via one main breaker"], 1],
    ["Which calculation do you perform for cable cross-section sizing?", ["Visual","Only load","Only length","Load, ambient temperature, bundling, voltage drop and short-circuit withstand"], 3],
    ["What is the disconnection condition for a 0.4 s requirement?", ["No requirement","Voltage measure only","Zs ≤ U₀ / Ia, where Ia is the trip current of the protective device","Time measure"], 2],
    ["How do you hand over a distribution unit?", ["Photo in the app","Just clean it","Visual inspection, measurement report, schematic in the cabinet, labels on circuits, NEN 1010 report","Don't label"], 2],
    ["Which documentation does a main contractor expect at electrical handover?", ["As-built drawings, schematics, measurement report, warranty statements, O&M","Only email","Nothing","Only the invoice"], 0],
    ["What is a KEMA-keur or KIWA certification?", ["Mandatory for fitters","Independent certificate for products/installations","A tool sticker","A safety mug"], 1],
    ["How do you create a daily plan for 6 fitters on a renovation project?", ["Everyone everywhere at once","On gut feeling","Decide upon arrival","Work packages per room/building, material supply, dependencies, buffer"], 3],
    ["What is a Permit-To-Work?", ["Toolbox form","A drawing","Pay slip","A document allowing specific work under conditions"], 3],
    ["How do you handle a construction deviation?", ["Decide alone","Hide it","Stop, log in the deviation register, agree a solution with supervisor/engineering","Push through"], 2],
    ["Which protection do you plan for a server room?", ["RCD 300 mA","Dedicated TN-S distribution board with redundancy, UPS, monitoring, early fire detection","Only one breaker","No protection"], 1],
    ["What is a short-circuit current calculation?", ["Voltage measure","Inspection measure","Calculation of Ik max/min to dimension protections correctly","Power measure"], 2],
    ["Which software packages do you know for installation design?", ["Photoshop","Word","Excel","Stabicad, Revit MEP, AutoCAD MEP"], 3],
    ["What agreements do you make with the main supervisor about access in heritage rooms?", ["Random","Afterwards","Time slots, supervision, protective measures for floors/walls, registration","None"], 2],
    ["What does 'final inspection' (NEN 1010) include?", ["Only measurements","Visual and functional check + measurements + report","Only the invoice","Visual only"], 1],
    ["How do you report progress to the supervisor?", ["Daily: progress, problems, planning, blockers — in a fixed format","Random","Don't","Monthly"], 0],
    ["How do you handle additional work flagged by an assistant fitter?", ["Carry it out immediately","Assess, log in the variation register, align with supervisor before execution","Ignore","Call the client"], 1],
    ["What is the correct commissioning sequence?", ["Energise immediately","Visual only","Visual → verify dead → potential/earth → insulation → energise → function","Random"], 2],
    ["How do you divide responsibilities in your crew?", ["Random","By age","Based on competencies (NEN 3140 level), with assistant fitters supervised by VP","Only by seniority"], 2],
    ["What is an electrical operating room per NEN 1010?", ["A general toilet","A meeting room","A room with specific requirements for access and competent operation","A storage room"], 2],
    ["What is BHV and how does it relate to your role?", ["A NEN standard","Company Emergency Response — the lead fitter is usually a co-responder and knows where AEDs are","Not relevant","A software package"], 1],
    ["Which first-aid steps do you follow for electrocution?", ["Apply a plaster","Run away","Cut power, call 112, perform CPR until help arrives","Touch the patient without disconnecting"], 2],
    ["How do you align with mechanical fitters when working simultaneously (climate ceilings)?", ["Plan the work order, do not cross cable trays and cooling/CH pipes at critical points","Only at the end of the project","Everyone on their own","Only on Friday"], 0],
    ["What is a snag (handover point)?", ["A toolbox note","Toolbox","A screw","An associated work/repair item on the snag list"], 3],
    ["What do you do after a near-miss?", ["Log immediately, root cause analysis, action, communicate lessons learned","Don't report","Only log on real accidents","Keep quiet"], 0],
    ["How do you align with the supplier for custom work in a heritage room?", ["Buy off-the-shelf","At the last minute","Random choice","Specs locked early, mock-up if needed, lead times in the schedule"], 3],
    ["What is an RI&E?", ["Risk Inventory and Evaluation — mandatory document on the construction site","A type of meter","A finance form","A drawing"], 0],
    ["What is your role in tool inspection?", ["Only occasionally","None","Only on complaints","Ensure valid NEN 3140 stickers, take defective tools out of circulation immediately"], 3],
    ["How do you validate the connection capacity for a new installation?", ["Calculated load + simultaneity factor → agreement with the grid operator","Estimate","Market value","Maximum value"], 0],
    ["What is a work package?", ["A pay slip","A defined set of work with scope, materials, time and planning","A bag","A screw set"], 1],
    ["What is a construction meeting?", ["Social moment","Periodic meeting between execution and parties to discuss progress and issues","Break","Official opening"], 1],
    ["How do you handle end-user complaints during a trial run?", ["On your own","Ignore","Log, prioritise, resolve methodically and feed back","Endlessly fix immediately"], 2],
    ["What is a digital twin in renovation projects?", ["A type of cable","A measurement device","A form","Digital model that runs in sync with the physical building, for maintenance"], 3],
    ["What is a SCIOS inspection?", ["A mandatory game","Independent inspection of technical installations for safety","A software inspection","A music inspection"], 1],
    ["What is an F-gases certificate and is it relevant for you?", ["For refrigerant handling — relevant for mechanical cooling work, not for electrical","Mandatory for electricians","Doesn't exist","Part of NEN 1010"], 0],
    ["Which planning approach do you use for a renovation across 7 buildings?", ["From back to front","One plan, all buildings","Spontaneous per day","Phase planning per building with dependencies, critical-path analysis"], 3],
    ["How do you report a safety incident?", ["Per the RI&E protocol, in the incident register, with immediate measures and review","Verbally only","Don't report","After a week"], 0],
    ["What is your strategy when materials are not on time?", ["Buffer work packages, alternatives, contact with procurement/supervisor","Random other work","People go home","Accept standstill"], 0],
    ["Which safety measure do you take when working alongside the public (continuous use)?", ["Only work at night","Only behind a lock","Cordon off the work area, limit dust and noise, communicate to users","Nothing"], 2],
    ["What is a VCA-VOL?", ["A type of crane","Safety Certification for Operational Supervisors — required for the lead fitter","A software licence","A welding diploma"], 1],
    ["How do you keep your crew motivated on a long renovation?", ["Do nothing","Clear goals, recognition, short feedback cycles, room to learn","Yell loudly","Bonus afterwards"], 1],
    ["Which protection is mandatory for sockets in damp areas?", ["Only ventilation","30 mA RCD + IP-rated materials","None","Only an MCB"], 1],
    ["What do you do if you spot a design error in the drawing?", ["Document, report to the design party, agree a solution before execution","Make up your own","Ignore","Continue unsafely"], 0],
    ["What is your role in 'sustainable demolition' of existing electrical work?", ["Separate materials for reuse/recycling, follow the asbestos protocol, register","Burn","All in one container","Throw aside"], 0],
  ],

  /* ════════════════════════════════════════════════════════════════════════
     MECHANICAL — ASSISTANT FITTER (50 questions)
     ════════════════════════════════════════════════════════════════════════ */
  'W-hulpmonteur': [
    ["Which tool do you use to bend copper pipes?", ["Pipe bender (manual or mechanical)","Drill","Pliers","Hammer"], 0],
    ["Which joining method is NOT an option on this project?", ["Compression couplings","Welding (total welding ban)","Soldering with an appropriate process","Press fitting"], 1],
    ["Why is there a total welding ban on this project?", ["Wooden floors — fire risk","Too expensive","No reason","No suitable welding equipment available"], 0],
    ["What is a press fitting?", ["A welded joint","A threaded joint","A rubber transition","A fitting that is permanently pressed onto the pipe with a pressing tool"], 3],
    ["Which tool do you use to press copper pipes?", ["Screwdriver","Spanner","Press tool with the correct press jaw (M, V or TH profile)","Adjustable wrench"], 2],
    ["What is the difference between flow and return in central heating?", ["No difference","Flow is thicker","Return is warmer","Flow is hot water from the boiler, return is cooled water back"], 3],
    ["What colour are flow pipes often marked with?", ["Blue","Red","Green","Yellow"], 1],
    ["What colour are return pipes often marked with?", ["Yellow","Blue","Red","Green"], 1],
    ["What is a T-fitting?", ["A fitting where three pipes meet","A type of meter","A type of valve","A support tool"], 0],
    ["Which materials may you use for drinking-water pipes?", ["Garden hose","Standard PVC","KIWA-certified (e.g. copper, stainless steel, multilayer-PEX)","Lead"], 2],
    ["What is pipe insulation?", ["Protective layer against rats","Advertising","Decoration","Material to prevent heat loss or condensation"], 3],
    ["Which basic tool do you use for threaded pipe joints?", ["Spanner/ring spanner or pipe wrench","Soldering iron","Drill","Hammer"], 0],
    ["What is teflon tape (PTFE tape)?", ["Insulation material","Cleaning agent","UV protection layer","Sealing material for threads"], 3],
    ["Which tool do you use to cut a pipe?", ["Jigsaw","Circular saw","Wood saw","Pipe cutter or fine metal saw"], 3],
    ["What do you do after sawing a copper pipe?", ["Remove burrs (inside and outside)","Connect immediately","Wet it","Paint it"], 0],
    ["Which PPE do you use when pressing/sawing pipes?", ["Safety glasses and gloves","None","Just helmet","Just earplugs"], 0],
    ["What do you do before operating a valve?", ["Ignore","Open hard","Check what's downstream, inform client/colleagues, open slowly","Run away"], 2],
    ["How do you tell a gas/water line from a drinking-water line?", ["By shape","By markings, colour and certification — when in doubt, do not connect yourself","On gut feeling","No difference"], 1],
    ["What is a climate ceiling?", ["Ceiling with integrated heating/cooling system (water- or air-fed)","Decorative ceiling","Acoustic ceiling","Sound-damping ceiling"], 0],
    ["Which pipe sizes are common in central-heating installations?", ["15, 18, 22, 28 mm copper or comparable PEX/multilayer","Only 6 mm","Only 50 mm","DN 100"], 0],
    ["What is a prefab pipe unit?", ["A meter","A type of valve","An insulation material","A pipe module pre-assembled in the factory, only coupled on site"], 3],
    ["What is the function of an air vent?", ["Lets air escape from the central-heating system","Fire protection","Sound damping","Water drainage"], 0],
    ["What is a manifold/distribution station?", ["Type of meter","Central point for distributing CH/cold water to circuits","Reduction device","Type of insulation"], 1],
    ["What is a pressure-reducing valve?", ["Filters water","Heats water","Reduces water pressure to a lower stable value","Stops water"], 2],
    ["In which direction do you usually tighten a thread?", ["Anticlockwise","Clockwise","Doesn't matter","Diagonal"], 1],
    ["What is leak detection?", ["Type of insulation","A filter","Sensor / system that signals leaks and shuts off water","Type of valve"], 2],
    ["What is a siphon (trap)?", ["S-shaped trap under drains to block sewer odour","Pump","Filter","Valve"], 0],
    ["What material is often used for sewage drainage in modern buildings?", ["Copper","Stainless steel","PVC or PP","Aluminium"], 2],
    ["Which PPE applies to working on a scaffold?", ["Just helmet","Helmet, shoes, harness if open side","Nothing","Just gloves"], 1],
    ["What is hard solder vs soft solder?", ["Hard solder is for PVC","Hard solder >450°C; soft solder <450°C — different applications","No difference","Soft solder is for steel"], 1],
    ["Do you use open-flame soldering on this project?", ["No, not without a hot-work permit; usually press fittings are used due to the welding ban","Only on Wednesdays","Yes, always","Only at night"], 0],
    ["What is a pressure test?", ["A cleaning","Test where the piping system is brought to pressure to check for leaks","A temperature measurement","An acoustic test"], 1],
    ["What is condensation?", ["A gas","A cleaning agent","Moisture that forms when a cold surface is exposed to humid air","An insulation"], 2],
    ["What do you do when there is a water leak during work?", ["Mop the floor","Close the main shut-off, secure the situation, report","Keep working","Nothing"], 1],
    ["Which pipes are often found in a service shaft?", ["CH, cooling, water, sewer, gas (separated)","Only sewer","Only electrical","Nothing"], 0],
    ["What is an air handling unit (AHU)?", ["A fan","A unit that conditions ventilation air (filter, heat, cool)","An extraction hood","An air conditioner"], 1],
    ["What is a radiator valve?", ["Type of filter","Sensor","Type of pump","Regulates the water flow through a radiator"], 3],
    ["What shape does a compression coupling have?", ["Straight piece","T-piece","Bend","Conical sealing ring with a coupling nut"], 3],
    ["Which size spanner do you use for a 22 mm coupling nut?", ["8 mm","Ring/open-end spanner 24 mm or pipe wrench","30 mm","13 mm"], 1],
    ["What is the difference between press fitting and compression fitting?", ["Press is removable","Compression is permanent","No difference","Press fitting is permanent (press tool); compression is removable"], 3],
    ["What is a convector?", ["A sensor","A type of lamp","A heater that warms air via natural or forced convection","A filter"], 2],
    ["Which insulation is often used around cold-water pipes?", ["Closed-cell flexible insulation (Armaflex type) against condensation","Dust","Open glass wool","None"], 0],
    ["What is a condensate drain?", ["Drainage of condensate water from an air conditioner or AHU","A valve","Foul-water drain","Rainwater"], 0],
    ["What is a drain valve?", ["A meter","An insulation","A sensor","A point where you empty or flush a system"], 3],
    ["How do you mark pipes after installation?", ["Nothing","With tape","With marker","With standardised pipe stickers/coloured rings (medium, direction, pressure)"], 3],
    ["What do you do with waste (lead, copper, plastic)?", ["All in one bin","Take it home","Burn","Sort into the correct container; copper separate due to value/recycling"], 3],
    ["What is the best moment to put a pipe under pressure?", ["Immediately","At end of day","When raining","After visual inspection and pressure test per work instruction"], 3],
    ["Which tools may NOT be used on this project?", ["Pipe cutter","Spanner","Press tool","Open-flame equipment (welders, torches) without a permit"], 3],
    ["How do you align daily with the lead fitter?", ["Only by email","Only on Fridays","Short morning briefing, task division, special items, end-of-day feedback","Don't"], 2],
    ["How do you handle an English-speaking supervisor colleague?", ["Ignore","In dialect","Call a translation agency","Communicate in clear English, use drawings and pictograms"], 3],
  ],

  /* ════════════════════════════════════════════════════════════════════════
     MECHANICAL — FITTER (50 questions)
     ════════════════════════════════════════════════════════════════════════ */
  'W-monteur': [
    ["What is a 4-pipe climate system?", ["Separate flow/return for both heating and cooling — simultaneously possible","Two pipes","One pipe","Four water-purification pipes"], 0],
    ["What is a 2-pipe climate system?", ["Four pipes","No pipes","One flow and one return, either heating or cooling","Three pipes"], 2],
    ["Which ISSO publication covers central-heating installations in residential buildings?", ["ISO 9001","ISSO 51","NEN 3140","NEN 1010"], 1],
    ["Which ISSO publication covers cooling generation and distribution?", ["ISSO 30","ISSO 80","ISSO 17","ISSO 75"], 3],
    ["Which refrigerant falls under F-gas regulations?", ["Water (H2O)","HFCs such as R410A, R32, R134a","Salt","Air"], 1],
    ["Who may carry out work on refrigerant systems?", ["Anyone","Nobody","Only electricians","Certified person (F-gas STEK / equivalent)"], 3],
    ["What is a 2-pipe climate ceiling?", ["Ceiling with a radiator","Ceiling with 4 pipes","Ceiling with an air duct","Ceiling with flow and return coupled in a 2-pipe system"], 3],
    ["What is hydraulic balancing in central heating?", ["Pump testing","Filtering","Pressure reduction","Distribution of water flow so each circuit gets enough flow"], 3],
    ["Which device performs hydraulic balancing?", ["Built-in balancing/regulating valve (e.g. Tacosetter, STAD/STAP-V)","Pump","Pressure reducer","Filter"], 0],
    ["What is a differential pressure controller?", ["Heats water","Stops water","Keeps the differential pressure across a circuit constant","Filters air"], 2],
    ["Which method tests a pressure pipe?", ["Switch on the pump","Visual only","Hit with a hammer","Pressure test with the correct medium and duration per standard"], 3],
    ["What maximum continuous temperature does standard PEX pipe tolerate?", ["250 °C","20 °C","150 °C","≈ 70-85 °C continuous, briefly higher"], 3],
    ["How do you size the pipe diameter for a heating circuit?", ["Guess","Based on flow rate, pressure drop, velocity (m/s) and length","Always 22 mm","Standard table without context"], 1],
    ["Which maximum water velocity is common in distribution piping?", ["10 m/s","5 m/s","≈ 1.0 m/s to limit noise and erosion","No limit"], 2],
    ["What is a three-way valve?", ["Mixes or distributes two water streams for temperature control","A pump","A filter","An air vent"], 0],
    ["What is a two-way valve?", ["A filter","Open/close valve for one pipe (often modulating control)","A distributor","A pump"], 1],
    ["Which valve is suitable for both balancing and shutoff?", ["Slide valve","Butterfly only","Ball valve only","Balancing valve with measuring nipples (e.g. STAD)"], 3],
    ["What is an expansion vessel?", ["Vessel that absorbs the volume expansion of CH water","Pump","Pressure reducer","Filter"], 0],
    ["Which pre-charge pressure do you use for a typical residential CH expansion vessel?", ["Not relevant","Always 5 bar","Static height (m) / 10 + 0.3 bar (guideline)","Always 0 bar"], 2],
    ["What is a safety valve?", ["Pumps","Filters","Protects the installation against overpressure by venting","Mixes"], 2],
    ["Which refrigerant line is usually larger, suction or liquid line?", ["Suction line is larger (gas, lower pressure/density)","Equal","No line exists","Liquid is larger"], 0],
    ["What is a dry cooler?", ["Outdoor unit that releases heat to outside air without water spraying","A pump","A mixing valve","A filter"], 0],
    ["Which medium does a wet-cooled climate ceiling typically use?", ["Oil","Direct CO2","Steam","Chilled water (low-salinity, optionally with glycol)"], 3],
    ["What is the 'free cooling' principle?", ["Heating on","Compressor always on","A type of pump","Use outside air/water to cool the building without a mechanical compressor"], 3],
    ["What is a condensate pump?", ["Pumps CH water","Pumps condensate water from AC/AHU to the drain","Fire-extinguishing system","Sewer ventilation"], 1],
    ["Which insulation class does a cold-water pipe in a damp location require?", ["Closed cell (μ ≥ 7000) and correct thickness against condensation","Open glass wool","None","Tape"], 0],
    ["What is an EPB report?", ["A welding report","A safety inspection","Energy performance calculation — relevant for handover","A quotation"], 2],
    ["Which MERV/EU filter class fits good office ventilation?", ["No filter","G2","Currently ISO ePM1 / ePM2.5 (was F7-F9)","C0"], 2],
    ["What is balanced ventilation?", ["WTW: equal supply and exhaust quantities, with heat recovery","Only supply","No ventilation","Only exhaust"], 0],
    ["What is WTW?", ["Heat recovery from ventilation return","Water-draught exchanger","Wattmeter group","Not an abbreviation"], 0],
    ["Which steps belong to commissioning a climate ceiling?", ["Flush, vent, pressure test, balance, BMS commissioning","Switch on directly","Visual check only","Nothing specific"], 0],
    ["What is a utility connection (gas/electricity/water)?", ["Connection from public utility to the meter cabinet","Private pipe","Sewer","Roof pipe"], 0],
    ["What is a guide bracket/clip for pipes?", ["A fixing that allows thermal movement","Filter","Valve","Pump"], 0],
    ["How do you fix piping to a wooden substrate on this project?", ["Nailing","Glue","With suitable screw/clip systems (no welded fixings)","Welding"], 2],
    ["Which water temperature is typical for cooling via a climate ceiling?", ["6 °C flow","45 °C flow","Flow 14-16 °C, return 16-18 °C, above the dew point","30 °C flow"], 2],
    ["What is dew-point control?", ["A safety valve","An acoustic seal","Preventing water temperature from going below the dew point to avoid condensation","A filter"], 2],
    ["What is a pressure vessel (CH)?", ["Synonym for membrane expansion vessel","A tank for hot water","A valve","A storage tank"], 0],
    ["Which instrument measures air flow?", ["Voltmeter","Multimeter","Thermohygrometer","Hot-wire / vane anemometer or flow-measuring grid"], 3],
    ["Which heat meter do you use for billing measurement?", ["Voltmeter","MID-certified heat meter (flow + ΔT)","Pressure meter","Water meter"], 1],
    ["What is a 'low-loss header' / open distributor?", ["Filter","Fire damper","Hydraulic decoupling between primary and secondary circuits","Sensor"], 2],
    ["What is BIM and how do you use it?", ["Excel","A screw","Building Information Modeling — 3D model + data, for coordination and execution","A measurement device"], 2],
    ["Which acoustic requirements apply in heritage rooms on this project?", ["No requirements","Strict — installations as quiet as possible; isolation and damping","Only at night","Highest noise allowed"], 1],
    ["What is a self-regulating thermostatic radiator valve?", ["Pump","Filter","Radiator valve that regulates room temperature per room","Sensor"], 2],
    ["Which procedure do you follow for a leak in a heritage room?", ["Shut off immediately, provide containment, inform heritage authority/supervisor","Hope it dries","Ignore","Keep working"], 0],
    ["What is a discharge pipe on a safety valve?", ["A filter pipe","Guided drain for water during venting, to a visible point","A return pipe","A vent"], 1],
    ["What is a gas pressure test?", ["With water","With compressed air","Do it yourself","NOT allowed by a mechanical fitter without certification — only by an accredited installer"], 3],
    ["Which valve separates two building sections during renovation?", ["Fire damper","None","Filter","Section valves at a central distribution point"], 3],
    ["What is frost protection?", ["Filter","Pump","Control that protects the installation against freezing","A valve"], 2],
    ["Which documentation belongs to mechanical handover?", ["Not required","Photos via WhatsApp","O&M manual, as-built, pressure-test report, balancing report, certificates","Only the invoice"], 2],
    ["How do you align with the electrical fitter on a climate ceiling?", ["Don't","Only at handover","Own plan","Coordinate sensor and connection points (mechanical) with the electrical control system (KNX/MOD-bus)"], 3],
  ],

  /* ════════════════════════════════════════════════════════════════════════
     MECHANICAL — LEAD FITTER (50 questions)
     ════════════════════════════════════════════════════════════════════════ */
  'W-chef': [
    ["What is your role at climate-ceiling commissioning?", ["Just watch","Coordinate flushing, pressure test, balancing, BMS test, handover","No role","Own work"], 1],
    ["Which ISSO guideline for hydraulic balancing do you know?", ["ISSO 50/57 (CH/cooling) and publications on hydraulic balancing","NEN 1010","NEN 3140","ISO 27001"], 0],
    ["Which responsibility do you have for F-gases on your crew?", ["Ensure certified personnel; keep a logbook","None","No logbook needed","Only administration"], 0],
    ["Which planning document do you coordinate daily?", ["Nothing","Work packages per room, material flow, interfaces with E/W/B","Only the weekly plan","Only the end date"], 1],
    ["Which risks do you check upfront in heritage rooms?", ["None","Only cost","Only time","Fire risk, damage to sensitive material, dust, heritage requirements"], 3],
    ["What is a coordination drawing?", ["A sketch","A drawing that aligns E, W and B in one layered system — prevents clashes","Text statement","An invoice"], 1],
    ["Which data do you secure for as-built?", ["Only old drawings","Only at the end","Capture changes during execution promptly in BIM/AutoCAD","Nothing"], 2],
    ["What do you do when a pressure test fails?", ["Continue","Lower the pressure","Ignore","Stop, locate, repair per procedure, retest + report"], 3],
    ["Which quality assurance do you apply on a climate ceiling?", ["Flushing protocol, pressure test, flow measurement, handover certificate per zone","None","Visual only","Spot check per month"], 0],
    ["Which BMS requirements do you know?", ["None","Only alarm","Flow, return and room sensors; valve positions; alarms; logging","Only flow"], 2],
    ["What is a function test?", ["Test where controls, protections and alarms are validated for operation","Flushing","Visual","Pressure test"], 0],
    ["Which Eurovent / SCOP / EER figures do you use for cooling?", ["Not relevant","Tariff","Energy efficiency cooling/heating under standardised conditions","Fire class"], 2],
    ["Which legal requirements apply to combustion installations?", ["None","SCIOS Scope 1/2/4 inspections + Activities Decree","Only ISO 9001","Only NEN 1010"], 1],
    ["Which air/water flow do you monitor during commissioning?", ["None","Only total","Measured per zone and compared with the design value, deviation <±10%","Only at peak"], 2],
    ["What is a snag list?", ["A screw set","List of open items to be fixed after handover","A software package","A pay slip"], 1],
    ["What is a construction logistics plan?", ["A software plan","Break plan","Fire-watch plan","Plan for material delivery, storage, removal in and around the construction site"], 3],
    ["Which information do you share with your crew every morning?", ["Today's goals, safety, E/W collaboration, material items","Nothing","Only location","Only times"], 0],
    ["What is your responsibility for hot work in a building with a welding ban?", ["Only at night","Allow sometimes","Allow no open flame; safeguard alternatives (press/couplings)","Yes when raining"], 2],
    ["How do you align with the main contractor (CWD)?", ["Weekly coordination, daily short updates, structure for deviations","Don't","Random","Monthly"], 0],
    ["Which training requirements for fitters on this The Hague project?", ["VCA, trade diploma, F-gases if refrigerant; periodic refreshers","None","Only language","Only driver's licence"], 0],
    ["What is a trial run (commissioning)?", ["A quotation","A corner iron","Period during which the installation is tested under operating conditions","A measuring instrument"], 2],
    ["What do you do with suspected asbestos material?", ["Stop immediately, secure the crew, have a specialist firm remediate","Continue carefully","Put on a small mask","Tamp it down"], 0],
    ["Which steps do you follow for a contamination risk in the water pipe?", ["Nothing","Add cola","Flushing protocol per ISSO 55-1, microbiological samples if required","Visual only"], 2],
    ["Which measurements do you report at hydraulic balancing?", ["Only temperature","Flow, pressure drop per zone, authority, set values — documented","Only the pump","None"], 1],
    ["What is the authority of a control valve?", ["A rank","Ratio of valve loss to total circuit loss (guideline ≥ 0.3)","Not a concept","A pressure class"], 1],
    ["How do you monitor progress with multiple crews across 7 buildings?", ["Phase planning, milestones, weekly review, dashboards and LMRAs","Spreadsheet without review","On gut feeling","Nothing"], 0],
    ["Which documentation do you require from a prefab supplier?", ["Photo by email","Nothing","Drawings, material certificates, pressure-test certificates, identification","Only the invoice"], 2],
    ["What is a lock-out/tag-out (LOTO) procedure for mechanical work?", ["Only for E electrical","Not needed","Pump/boiler off, valves closed and labelled, energy sources secured","Only for gas"], 2],
    ["What is your role at a safety incident in your crew?", ["First aid, secure the situation, report, root cause and prevention","Think it through afterwards","Cover it up","Only report falls"], 0],
    ["Which knowledge do you expect of a mechanical fitter regarding noise transmission?", ["None","Isolate pump/pipe vibration, dampers, correct fixings","Only technically interesting","Only visual"], 1],
    ["What is your strategy when design and constructability deviate?", ["Log the issue, propose a solution, align with engineer/supervisor, send an RFI","Ignore","Only report afterwards","Change it yourself"], 0],
    ["What is an RFI?", ["Request For Information — formal question to the design team","A measurement","A valve","A type of tap"], 0],
    ["How do you align the electrical-mechanical interface for a climate ceiling?", ["Only on the day","Visual only","Don't","Plan sensors, valves, controllers and wiring integrally with the electrical lead fitter"], 3],
    ["What are your critical commissioning tests?", ["Pressure test, flushing, flow, temperature, controls, alarms","None","Only pressure test","Only temperature"], 0],
    ["Which environmental requirements apply for refrigerant work?", ["Only cost","Only time","None","GWP-aware working, leak detection, correct recovery, F-gas registration"], 3],
    ["Which information is on a test certificate?", ["Nothing","Test medium, pressure, duration, result, date, signature","Only price","Only text"], 1],
    ["What is sequence control on climate ceilings?", ["Cascade/sequence control between heating, neutral band and cooling","Always off","Always on","Random"], 0],
    ["Which risks do you have on a renovation with continuous use by occupants?", ["Noise/dust, fire safety, escape routes, security, image","None","Only cost","Only time"], 0],
    ["Which escalation route do you follow on stagnation?", ["Don't escalate","Direct to senior management","To the client","First the supervisor, then the main supervisor, then the project manager"], 3],
    ["How do you coach an assistant fitter who makes mistakes?", ["Safe feedback, demonstrate, short cycle, gradually more responsibility","Send away","Punishment roster","Ignore"], 0],
    ["What is your policy for PPE checks?", ["Nothing","Once a month","Visual every morning, cleanliness, correct size and NEN inspection where required","On complaint"], 2],
    ["What is your role with sub-contractors (e.g. insulation crew)?", ["Only at the end","Plan, check methods, quality check, interfaces","Only the invoice","Nothing"], 1],
    ["Which documentation do you hand over at final handover?", ["Only the invoice","As-built, O&M, certificates, balancing reports, warranties, snag list","Nothing","Verbally"], 1],
    ["What is a commissioning manager (CxM)?", ["A software package","A tap","An independent role that coordinates the entire commissioning process","A type of meter"], 2],
    ["What is your strategy for hot days during execution?", ["Skip break","Faster pace","Don't","Adjust working hours, water, shade, signal heat stress"], 3],
    ["Which records do you keep per building?", ["Logbook with progress, deviations, decisions, photos","Only total","End of project","Don't"], 0],
    ["How do you measure success of your execution?", ["Safety, quality, planning, customer satisfaction, lessons learned","Only quality","Only cost","Only time"], 0],
    ["What is a snagging walk?", ["A type of training","A walk","Inspection round just before handover to identify remaining items","A measurement"], 2],
    ["Which collaboration with Emergency Response is important to you?", ["Only smoke detector","Escape routes free, fire-damper positions, hot-work permit, user information","Only at the time of fire","Don't"], 1],
    ["What is your role as lead fitter in improvement projects (lessons learned)?", ["Only meetings","Forget","Capture lessons, share with team and company, structurally improve","Nothing"], 2],
  ],

};

/* ============================================================================
   IMAGE-RECOGNITION QUESTIONS — 2 randomly drawn per test session
   ============================================================================ */
const IMAGE_QUESTIONS_EN = {
  'E-hulpmonteur': [
    { vraag: "Which component do you see in the image?", img: "images/img_E-hulpmonteur_1.png", opties: ["Wall socket","Miniature circuit breaker","Junction box","Dimmer"], correct: 1 },
    { vraag: "Which part is shown here?", img: "images/img_E-hulpmonteur_2.jpeg", opties: ["Earth wire","Wall switch","Cable tray","Main switch"], correct: 1 },
    { vraag: "Which electrical component do you see?", img: "images/img_E-hulpmonteur_3.jpeg", opties: ["Distribution board","Plug","Transformer","Motion sensor"], correct: 0 },
  ],
  'E-monteur': [
    { vraag: "Which component do you see in the image?", img: "images/img_E-monteur_1.jpeg", opties: ["Residual current device","Miniature circuit breaker","Magnetic contactor","Transformer"], correct: 0 },
    { vraag: "Which component do you see in the image?", img: "images/img_E-monteur_2.jpeg", opties: ["Relay","Magnetic contactor","Final circuit","Earth bar"], correct: 2 },
    { vraag: "Which component do you see in the image?", img: "images/img_E-monteur_3.png", opties: ["Main switch","Miniature circuit breaker","Fuse","Residual current device"], correct: 0 },
  ],
  'E-chef': [
    { vraag: "Which component do you see in the image?", img: "images/img_E-chef_1.png", opties: ["Frequency converter","Power circuit breaker","Magnetic contactor","Soft starter"], correct: 1 },
    { vraag: "Which component do you see in the image?", img: "images/img_E-chef_2.png", opties: ["RCBO","Motor protection switch","Power circuit breaker","Relay"], correct: 1 },
    { vraag: "Which industrial component do you see in the image?", img: "images/img_E-chef_3.png", opties: ["PLC module","Miniature circuit breaker","Transformer","Time relay"], correct: 0 },
  ],
  'W-hulpmonteur': [
    { vraag: "Which fitting is shown here?", img: "images/img_W-hulpmonteur_1.jpeg", opties: ["Press coupling","Socket joint","Elbow coupling","Flange joint"], correct: 0 },
    { vraag: "Which part do you see in the image?", img: "images/img_W-hulpmonteur_2.jpeg", opties: ["Ball valve","T-fitting","Flexible hose","Radiator valve"], correct: 0 },
    { vraag: "Which connection is applied here?", img: "images/img_W-hulpmonteur_3.jpeg", opties: ["Flange joint","Compression couplings","Press joint","Solder joint"], correct: 1 },
  ],
  'W-monteur': [
    { vraag: "Which fitting is shown here?", img: "images/img_W-monteur_1.png", opties: ["Press coupling","Socket joint","Elbow coupling","Reducer"], correct: 3 },
    { vraag: "Which valve do you see in the image?", img: "images/img_W-monteur_2.jpeg", opties: ["Balancing valve","Check valve","Safety valve","Ball valve"], correct: 0 },
    { vraag: "Which component belongs to this piping installation?", img: "images/img_W-monteur_3.jpeg", opties: ["Expansion vessel","Heat exchanger","Circulation pump","Pressure regulator"], correct: 2 },
  ],
  'W-chef': [
    { vraag: "Which industrial connection is shown here?", img: "images/img_W-chef_1.jpeg", opties: ["Victaulic coupling","Flange joint","Press joint","Solder joint"], correct: 1 },
    { vraag: "Which installation component is used here for pressure regulation?", img: "images/img_W-chef_2.jpeg", opties: ["Expansion vessel","Pressure-reducing valve","Safety valve","Circulation pump"], correct: 1 },
  ],
};
